/* application.c generated by valac 0.28.1, the Vala compiler
 * generated from application.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * application.vala
 The MIT License (MIT)

 Copyright (c) 2015 Vinibo

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define TERMITES_TYPE_APPLICATION (termites_application_get_type ())
#define TERMITES_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_APPLICATION, TermitesApplication))
#define TERMITES_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_APPLICATION, TermitesApplicationClass))
#define TERMITES_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_APPLICATION))
#define TERMITES_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_APPLICATION))
#define TERMITES_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_APPLICATION, TermitesApplicationClass))

typedef struct _TermitesApplication TermitesApplication;
typedef struct _TermitesApplicationClass TermitesApplicationClass;
typedef struct _TermitesApplicationPrivate TermitesApplicationPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _TermitesApplication {
	GObject parent_instance;
	TermitesApplicationPrivate * priv;
};

struct _TermitesApplicationClass {
	GObjectClass parent_class;
};


static gpointer termites_application_parent_class = NULL;

GType termites_application_get_type (void) G_GNUC_CONST;
enum  {
	TERMITES_APPLICATION_DUMMY_PROPERTY
};
#define TERMITES_APPLICATION_APPLICATION_NAME "termites"
#define TERMITES_APPLICATION_APPLICATION_MAJOR 0
#define TERMITES_APPLICATION_APPLICATION_MINOR 0
#define TERMITES_APPLICATION_APPLICATION_BUILD 500
TermitesApplication* termites_application_new (void);
TermitesApplication* termites_application_construct (GType object_type);
gchar* termites_application_get_version_string (void);
gchar* termites_application_generate_file_header (void);
gboolean termites_application_is_compatible_version (const gchar* version);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


TermitesApplication* termites_application_construct (GType object_type) {
	TermitesApplication * self = NULL;
#line 39 "/home/vincent/Source/Vala/Termites/src/application.vala"
	self = (TermitesApplication*) g_object_new (object_type, NULL);
#line 39 "/home/vincent/Source/Vala/Termites/src/application.vala"
	return self;
#line 85 "application.c"
}


TermitesApplication* termites_application_new (void) {
#line 39 "/home/vincent/Source/Vala/Termites/src/application.vala"
	return termites_application_construct (TERMITES_TYPE_APPLICATION);
#line 92 "application.c"
}


gchar* termites_application_get_version_string (void) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp0_ = g_strdup_printf ("%i", TERMITES_APPLICATION_APPLICATION_MAJOR);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp1_ = _tmp0_;
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp2_ = g_strconcat (_tmp1_, ".", NULL);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp3_ = _tmp2_;
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp4_ = g_strdup_printf ("%i", TERMITES_APPLICATION_APPLICATION_MINOR);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp5_ = _tmp4_;
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp6_ = g_strconcat (_tmp3_, _tmp5_, NULL);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp7_ = _tmp6_;
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp8_ = g_strconcat (_tmp7_, ".", NULL);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp9_ = _tmp8_;
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp10_ = g_strdup_printf ("%i", TERMITES_APPLICATION_APPLICATION_BUILD);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp11_ = _tmp10_;
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp12_ = g_strconcat (_tmp9_, _tmp11_, NULL);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp13_ = _tmp12_;
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_g_free0 (_tmp11_);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_g_free0 (_tmp9_);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_g_free0 (_tmp7_);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_g_free0 (_tmp5_);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_g_free0 (_tmp3_);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_g_free0 (_tmp1_);
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	result = _tmp13_;
#line 44 "/home/vincent/Source/Vala/Termites/src/application.vala"
	return result;
#line 156 "application.c"
}


gchar* termites_application_generate_file_header (void) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
#line 50 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp0_ = termites_application_get_version_string ();
#line 50 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp1_ = _tmp0_;
#line 50 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp2_ = g_strconcat (TERMITES_APPLICATION_APPLICATION_NAME ":", _tmp1_, NULL);
#line 50 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp3_ = _tmp2_;
#line 50 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp4_ = g_strconcat (_tmp3_, "\n", NULL);
#line 50 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp5_ = _tmp4_;
#line 50 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_g_free0 (_tmp3_);
#line 50 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_g_free0 (_tmp1_);
#line 50 "/home/vincent/Source/Vala/Termites/src/application.vala"
	result = _tmp5_;
#line 50 "/home/vincent/Source/Vala/Termites/src/application.vala"
	return result;
#line 188 "application.c"
}


gboolean termites_application_is_compatible_version (const gchar* version) {
	gboolean result = FALSE;
	gchar** decomposed_version = NULL;
	const gchar* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gint decomposed_version_length1 = 0;
	gint _decomposed_version_size_ = 0;
	gint major = 0;
	gchar** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	const gchar* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint minor = 0;
	gchar** _tmp6_ = NULL;
	gint _tmp6__length1 = 0;
	const gchar* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	gint build = 0;
	gchar** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	const gchar* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	gboolean _tmp12_ = FALSE;
	gboolean _tmp13_ = FALSE;
	gint _tmp14_ = 0;
#line 53 "/home/vincent/Source/Vala/Termites/src/application.vala"
	g_return_val_if_fail (version != NULL, FALSE);
#line 54 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp0_ = version;
#line 54 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp2_ = _tmp1_ = g_strsplit (_tmp0_, ".", 0);
#line 54 "/home/vincent/Source/Vala/Termites/src/application.vala"
	decomposed_version = _tmp2_;
#line 54 "/home/vincent/Source/Vala/Termites/src/application.vala"
	decomposed_version_length1 = _vala_array_length (_tmp1_);
#line 54 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_decomposed_version_size_ = decomposed_version_length1;
#line 56 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp3_ = decomposed_version;
#line 56 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp3__length1 = decomposed_version_length1;
#line 56 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp4_ = _tmp3_[0];
#line 56 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp5_ = atoi (_tmp4_);
#line 56 "/home/vincent/Source/Vala/Termites/src/application.vala"
	major = _tmp5_;
#line 57 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp6_ = decomposed_version;
#line 57 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp6__length1 = decomposed_version_length1;
#line 57 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp7_ = _tmp6_[1];
#line 57 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp8_ = atoi (_tmp7_);
#line 57 "/home/vincent/Source/Vala/Termites/src/application.vala"
	minor = _tmp8_;
#line 58 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp9_ = decomposed_version;
#line 58 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp9__length1 = decomposed_version_length1;
#line 58 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp10_ = _tmp9_[2];
#line 58 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp11_ = atoi (_tmp10_);
#line 58 "/home/vincent/Source/Vala/Termites/src/application.vala"
	build = _tmp11_;
#line 60 "/home/vincent/Source/Vala/Termites/src/application.vala"
	_tmp14_ = major;
#line 60 "/home/vincent/Source/Vala/Termites/src/application.vala"
	if (_tmp14_ <= TERMITES_APPLICATION_APPLICATION_MAJOR) {
#line 264 "application.c"
		gint _tmp15_ = 0;
#line 61 "/home/vincent/Source/Vala/Termites/src/application.vala"
		_tmp15_ = minor;
#line 61 "/home/vincent/Source/Vala/Termites/src/application.vala"
		_tmp13_ = _tmp15_ <= TERMITES_APPLICATION_APPLICATION_MINOR;
#line 270 "application.c"
	} else {
#line 60 "/home/vincent/Source/Vala/Termites/src/application.vala"
		_tmp13_ = FALSE;
#line 274 "application.c"
	}
#line 60 "/home/vincent/Source/Vala/Termites/src/application.vala"
	if (_tmp13_) {
#line 278 "application.c"
		gint _tmp16_ = 0;
#line 62 "/home/vincent/Source/Vala/Termites/src/application.vala"
		_tmp16_ = build;
#line 62 "/home/vincent/Source/Vala/Termites/src/application.vala"
		_tmp12_ = _tmp16_ <= TERMITES_APPLICATION_APPLICATION_BUILD;
#line 284 "application.c"
	} else {
#line 60 "/home/vincent/Source/Vala/Termites/src/application.vala"
		_tmp12_ = FALSE;
#line 288 "application.c"
	}
#line 60 "/home/vincent/Source/Vala/Termites/src/application.vala"
	result = _tmp12_;
#line 60 "/home/vincent/Source/Vala/Termites/src/application.vala"
	decomposed_version = (_vala_array_free (decomposed_version, decomposed_version_length1, (GDestroyNotify) g_free), NULL);
#line 60 "/home/vincent/Source/Vala/Termites/src/application.vala"
	return result;
#line 296 "application.c"
}


static void termites_application_class_init (TermitesApplicationClass * klass) {
#line 32 "/home/vincent/Source/Vala/Termites/src/application.vala"
	termites_application_parent_class = g_type_class_peek_parent (klass);
#line 303 "application.c"
}


static void termites_application_instance_init (TermitesApplication * self) {
}


GType termites_application_get_type (void) {
	static volatile gsize termites_application_type_id__volatile = 0;
	if (g_once_init_enter (&termites_application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TermitesApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) termites_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TermitesApplication), 0, (GInstanceInitFunc) termites_application_instance_init, NULL };
		GType termites_application_type_id;
		termites_application_type_id = g_type_register_static (G_TYPE_OBJECT, "TermitesApplication", &g_define_type_info, 0);
		g_once_init_leave (&termites_application_type_id__volatile, termites_application_type_id);
	}
	return termites_application_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



