/* fileHelper.c generated by valac 0.28.1, the Vala compiler
 * generated from fileHelper.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * fileHelper.vala
 The MIT License (MIT)

 Copyright (c) 2015 Vinibo

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdio.h>


#define TERMITES_TYPE_FILE_HELPER (termites_file_helper_get_type ())
#define TERMITES_FILE_HELPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_FILE_HELPER, TermitesFileHelper))
#define TERMITES_FILE_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_FILE_HELPER, TermitesFileHelperClass))
#define TERMITES_IS_FILE_HELPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_FILE_HELPER))
#define TERMITES_IS_FILE_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_FILE_HELPER))
#define TERMITES_FILE_HELPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_FILE_HELPER, TermitesFileHelperClass))

typedef struct _TermitesFileHelper TermitesFileHelper;
typedef struct _TermitesFileHelperClass TermitesFileHelperClass;
typedef struct _TermitesFileHelperPrivate TermitesFileHelperPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define TERMITES_TYPE_TERMITE_STORE (termites_termite_store_get_type ())
#define TERMITES_TERMITE_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStore))
#define TERMITES_TERMITE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStoreClass))
#define TERMITES_IS_TERMITE_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_TERMITE_STORE))
#define TERMITES_IS_TERMITE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_TERMITE_STORE))
#define TERMITES_TERMITE_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStoreClass))

typedef struct _TermitesTermiteStore TermitesTermiteStore;
typedef struct _TermitesTermiteStoreClass TermitesTermiteStoreClass;

#define TERMITES_TYPE_TERMITE_NODE (termites_termite_node_get_type ())
#define TERMITES_TERMITE_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNode))
#define TERMITES_TERMITE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNodeClass))
#define TERMITES_IS_TERMITE_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_TERMITE_NODE))
#define TERMITES_IS_TERMITE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_TERMITE_NODE))
#define TERMITES_TERMITE_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNodeClass))

typedef struct _TermitesTermiteNode TermitesTermiteNode;
typedef struct _TermitesTermiteNodeClass TermitesTermiteNodeClass;

struct _TermitesFileHelper {
	GObject parent_instance;
	TermitesFileHelperPrivate * priv;
};

struct _TermitesFileHelperClass {
	GObjectClass parent_class;
};


static gpointer termites_file_helper_parent_class = NULL;

GType termites_file_helper_get_type (void) G_GNUC_CONST;
enum  {
	TERMITES_FILE_HELPER_DUMMY_PROPERTY
};
void termites_file_helper_save_termites_tree (const gchar* file_path, GtkTreeStore* termites);
gchar* termites_application_generate_file_header (void);
GtkTreeModelForeachFunc termites_termite_store_generate_save_delegate (GDataOutputStream* file, void** result_target, GDestroyNotify* result_target_destroy_notify);
GType termites_termite_store_get_type (void) G_GNUC_CONST;
void termites_file_helper_load_termites_tree (const gchar* file_path, TermitesTermiteStore* termites);
gboolean termites_file_helper_is_acceptable_file (GDataInputStream* file_reader);
void termites_termite_store_clear_tree (TermitesTermiteStore* self);
GType termites_termite_node_get_type (void) G_GNUC_CONST;
TermitesTermiteNode* termites_termite_node_new_empty (void);
TermitesTermiteNode* termites_termite_node_construct_empty (GType object_type);
void termites_termite_node_set_name (TermitesTermiteNode* self, const gchar* value);
void termites_termite_node_set_host (TermitesTermiteNode* self, const gchar* value);
void termites_termite_node_set_port (TermitesTermiteNode* self, const gchar* value);
void termites_termite_node_set_username (TermitesTermiteNode* self, const gchar* value);
GtkTreeIter* termites_termite_store_convert_string_to_new_iter (TermitesTermiteStore* self, const gchar* path_to_convert);
void termites_termite_store_add_node (TermitesTermiteStore* self, TermitesTermiteNode* node, GtkTreeIter* position, GtkTreeIter* position_inserted);
void termites_file_helper_load_mremoteng_connections (TermitesFileHelper* self, const gchar* p_Filepath);
void termites_file_helper_load_putty_profile (TermitesFileHelper* self);
#define TERMITES_APPLICATION_APPLICATION_NAME "termites"
gboolean termites_application_is_compatible_version (const gchar* version);
TermitesFileHelper* termites_file_helper_new (void);
TermitesFileHelper* termites_file_helper_construct (GType object_type);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


void termites_file_helper_save_termites_tree (const gchar* file_path, GtkTreeStore* termites) {
	GFile* file = NULL;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	GFile* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	GFileOutputStream* file_stream = NULL;
	GFile* _tmp5_ = NULL;
	GFileOutputStream* _tmp6_ = NULL;
	GDataOutputStream* stream = NULL;
	GFileOutputStream* _tmp7_ = NULL;
	GDataOutputStream* _tmp8_ = NULL;
	GDataOutputStream* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	GtkTreeStore* _tmp12_ = NULL;
	GDataOutputStream* _tmp13_ = NULL;
	void* _tmp14_ = NULL;
	GDestroyNotify _tmp15_ = NULL;
	GtkTreeModelForeachFunc _tmp16_ = NULL;
	GtkTreeModelForeachFunc _tmp17_ = NULL;
	void* _tmp17__target = NULL;
	GDestroyNotify _tmp17__target_destroy_notify = NULL;
	GDataOutputStream* _tmp18_ = NULL;
	GError * _inner_error_ = NULL;
#line 37 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	g_return_if_fail (file_path != NULL);
#line 37 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	g_return_if_fail (termites != NULL);
#line 38 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp0_ = file_path;
#line 38 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp1_ = g_file_new_for_uri (_tmp0_);
#line 38 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	file = _tmp1_;
#line 40 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp2_ = file;
#line 40 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp3_ = g_file_query_exists (_tmp2_, NULL);
#line 40 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	if (_tmp3_) {
#line 157 "fileHelper.c"
		GFile* _tmp4_ = NULL;
#line 41 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_tmp4_ = file;
#line 41 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		g_file_delete (_tmp4_, NULL, &_inner_error_);
#line 41 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 41 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_g_object_unref0 (file);
#line 41 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 41 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			g_clear_error (&_inner_error_);
#line 41 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			return;
#line 173 "fileHelper.c"
		}
	}
#line 44 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp5_ = file;
#line 44 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp6_ = g_file_create (_tmp5_, G_FILE_CREATE_REPLACE_DESTINATION, NULL, &_inner_error_);
#line 44 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	file_stream = _tmp6_;
#line 44 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 44 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_g_object_unref0 (file);
#line 44 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 44 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		g_clear_error (&_inner_error_);
#line 44 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		return;
#line 192 "fileHelper.c"
	}
#line 45 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp7_ = file_stream;
#line 45 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp8_ = g_data_output_stream_new ((GOutputStream*) _tmp7_);
#line 45 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	stream = _tmp8_;
#line 47 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp9_ = stream;
#line 47 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp10_ = termites_application_generate_file_header ();
#line 47 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp11_ = _tmp10_;
#line 47 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	g_data_output_stream_put_string (_tmp9_, _tmp11_, NULL, &_inner_error_);
#line 47 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_g_free0 (_tmp11_);
#line 47 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 47 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_g_object_unref0 (stream);
#line 47 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_g_object_unref0 (file_stream);
#line 47 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_g_object_unref0 (file);
#line 47 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 47 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		g_clear_error (&_inner_error_);
#line 47 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		return;
#line 224 "fileHelper.c"
	}
#line 48 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp12_ = termites;
#line 48 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp13_ = stream;
#line 48 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp16_ = termites_termite_store_generate_save_delegate (_tmp13_, &_tmp14_, &_tmp15_);
#line 48 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp17_ = _tmp16_;
#line 48 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp17__target = _tmp14_;
#line 48 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp17__target_destroy_notify = _tmp15_;
#line 48 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	gtk_tree_model_foreach ((GtkTreeModel*) _tmp12_, _tmp17_, _tmp14_);
#line 48 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	(_tmp17__target_destroy_notify == NULL) ? NULL : (_tmp17__target_destroy_notify (_tmp17__target), NULL);
#line 48 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp17_ = NULL;
#line 48 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp17__target = NULL;
#line 48 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp17__target_destroy_notify = NULL;
#line 49 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp18_ = stream;
#line 49 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	g_output_stream_close ((GOutputStream*) _tmp18_, NULL, &_inner_error_);
#line 49 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 49 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_g_object_unref0 (stream);
#line 49 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_g_object_unref0 (file_stream);
#line 49 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_g_object_unref0 (file);
#line 49 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 49 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		g_clear_error (&_inner_error_);
#line 49 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		return;
#line 266 "fileHelper.c"
	}
#line 37 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_g_object_unref0 (stream);
#line 37 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_g_object_unref0 (file_stream);
#line 37 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_g_object_unref0 (file);
#line 274 "fileHelper.c"
}


void termites_file_helper_load_termites_tree (const gchar* file_path, TermitesTermiteStore* termites) {
	GFile* file = NULL;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	GFile* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	GFileInputStream* _tmp4_ = NULL;
	GFile* _tmp5_ = NULL;
	GFileInputStream* _tmp6_ = NULL;
	GDataInputStream* dis = NULL;
	GDataInputStream* _tmp7_ = NULL;
	GDataInputStream* _tmp8_ = NULL;
	gboolean _tmp9_ = FALSE;
	GError * _inner_error_ = NULL;
#line 53 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	g_return_if_fail (file_path != NULL);
#line 53 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	g_return_if_fail (termites != NULL);
#line 54 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp0_ = file_path;
#line 54 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp1_ = g_file_new_for_uri (_tmp0_);
#line 54 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	file = _tmp1_;
#line 56 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp2_ = file;
#line 56 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp3_ = g_file_query_exists (_tmp2_, NULL);
#line 56 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	if (!_tmp3_) {
#line 308 "fileHelper.c"
	}
#line 60 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp5_ = file;
#line 60 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp6_ = g_file_read (_tmp5_, NULL, &_inner_error_);
#line 60 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp4_ = _tmp6_;
#line 60 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 60 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_g_object_unref0 (file);
#line 60 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 60 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		g_clear_error (&_inner_error_);
#line 60 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		return;
#line 326 "fileHelper.c"
	}
#line 60 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp7_ = g_data_input_stream_new ((GInputStream*) _tmp4_);
#line 60 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	dis = _tmp7_;
#line 62 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp8_ = dis;
#line 62 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp9_ = termites_file_helper_is_acceptable_file (_tmp8_);
#line 62 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	if (_tmp9_) {
#line 338 "fileHelper.c"
		TermitesTermiteStore* _tmp10_ = NULL;
		gchar* line = NULL;
#line 63 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_tmp10_ = termites;
#line 63 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		termites_termite_store_clear_tree (_tmp10_);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		while (TRUE) {
#line 347 "fileHelper.c"
			gchar* _tmp11_ = NULL;
			GDataInputStream* _tmp12_ = NULL;
			gchar* _tmp13_ = NULL;
			gchar* _tmp14_ = NULL;
			const gchar* _tmp15_ = NULL;
			gchar** node_line = NULL;
			const gchar* _tmp16_ = NULL;
			gchar** _tmp17_ = NULL;
			gchar** _tmp18_ = NULL;
			gint node_line_length1 = 0;
			gint _node_line_size_ = 0;
			TermitesTermiteNode* node = NULL;
			TermitesTermiteNode* _tmp19_ = NULL;
			TermitesTermiteNode* _tmp20_ = NULL;
			gchar** _tmp21_ = NULL;
			gint _tmp21__length1 = 0;
			const gchar* _tmp22_ = NULL;
			TermitesTermiteNode* _tmp23_ = NULL;
			gchar** _tmp24_ = NULL;
			gint _tmp24__length1 = 0;
			const gchar* _tmp25_ = NULL;
			TermitesTermiteNode* _tmp26_ = NULL;
			gchar** _tmp27_ = NULL;
			gint _tmp27__length1 = 0;
			const gchar* _tmp28_ = NULL;
			TermitesTermiteNode* _tmp29_ = NULL;
			gchar** _tmp30_ = NULL;
			gint _tmp30__length1 = 0;
			const gchar* _tmp31_ = NULL;
			GtkTreeIter wasteland = {0};
			GtkTreeIter* new_position = NULL;
			TermitesTermiteStore* _tmp32_ = NULL;
			gchar** _tmp33_ = NULL;
			gint _tmp33__length1 = 0;
			const gchar* _tmp34_ = NULL;
			GtkTreeIter* _tmp35_ = NULL;
			TermitesTermiteStore* _tmp36_ = NULL;
			TermitesTermiteNode* _tmp37_ = NULL;
			GtkTreeIter* _tmp38_ = NULL;
			GtkTreeIter _tmp39_ = {0};
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp12_ = dis;
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp13_ = g_data_input_stream_read_line (_tmp12_, NULL, NULL, &_inner_error_);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp11_ = _tmp13_;
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
				_g_free0 (line);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
				_g_object_unref0 (dis);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
				_g_object_unref0 (_tmp4_);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
				_g_object_unref0 (file);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
				g_clear_error (&_inner_error_);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
				return;
#line 410 "fileHelper.c"
			}
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp14_ = _tmp11_;
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp11_ = NULL;
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_g_free0 (line);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			line = _tmp14_;
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp15_ = line;
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			if (!(_tmp15_ != NULL)) {
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
				_g_free0 (_tmp11_);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
				break;
#line 428 "fileHelper.c"
			}
#line 67 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp16_ = line;
#line 67 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp18_ = _tmp17_ = g_strsplit (_tmp16_, ",", 0);
#line 67 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			node_line = _tmp18_;
#line 67 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			node_line_length1 = _vala_array_length (_tmp17_);
#line 67 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_node_line_size_ = node_line_length1;
#line 70 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp19_ = termites_termite_node_new_empty ();
#line 70 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			node = _tmp19_;
#line 71 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp20_ = node;
#line 71 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp21_ = node_line;
#line 71 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp21__length1 = node_line_length1;
#line 71 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp22_ = _tmp21_[1];
#line 71 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			termites_termite_node_set_name (_tmp20_, _tmp22_);
#line 72 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp23_ = node;
#line 72 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp24_ = node_line;
#line 72 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp24__length1 = node_line_length1;
#line 72 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp25_ = _tmp24_[2];
#line 72 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			termites_termite_node_set_host (_tmp23_, _tmp25_);
#line 73 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp26_ = node;
#line 73 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp27_ = node_line;
#line 73 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp27__length1 = node_line_length1;
#line 73 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp28_ = _tmp27_[3];
#line 73 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			termites_termite_node_set_port (_tmp26_, _tmp28_);
#line 74 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp29_ = node;
#line 74 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp30_ = node_line;
#line 74 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp30__length1 = node_line_length1;
#line 74 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp31_ = _tmp30_[4];
#line 74 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			termites_termite_node_set_username (_tmp29_, _tmp31_);
#line 77 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp32_ = termites;
#line 77 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp33_ = node_line;
#line 77 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp33__length1 = node_line_length1;
#line 77 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp34_ = _tmp33_[0];
#line 77 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp35_ = termites_termite_store_convert_string_to_new_iter (_tmp32_, _tmp34_);
#line 77 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			new_position = _tmp35_;
#line 78 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp36_ = termites;
#line 78 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp37_ = node;
#line 78 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_tmp38_ = new_position;
#line 78 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			termites_termite_store_add_node (_tmp36_, _tmp37_, _tmp38_, &_tmp39_);
#line 78 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			wasteland = _tmp39_;
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_g_free0 (new_position);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_g_object_unref0 (node);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			node_line = (_vala_array_free (node_line, node_line_length1, (GDestroyNotify) g_free), NULL);
#line 66 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
			_g_free0 (_tmp11_);
#line 514 "fileHelper.c"
		}
#line 62 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_g_free0 (line);
#line 518 "fileHelper.c"
	} else {
		FILE* _tmp40_ = NULL;
#line 81 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_tmp40_ = stderr;
#line 81 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		fprintf (_tmp40_, "File not acceptable for this version");
#line 525 "fileHelper.c"
	}
#line 53 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_g_object_unref0 (dis);
#line 53 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_g_object_unref0 (_tmp4_);
#line 53 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_g_object_unref0 (file);
#line 533 "fileHelper.c"
}


void termites_file_helper_load_mremoteng_connections (TermitesFileHelper* self, const gchar* p_Filepath) {
#line 86 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	g_return_if_fail (self != NULL);
#line 86 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	g_return_if_fail (p_Filepath != NULL);
#line 542 "fileHelper.c"
}


void termites_file_helper_load_putty_profile (TermitesFileHelper* self) {
#line 90 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	g_return_if_fail (self != NULL);
#line 549 "fileHelper.c"
}


static gchar* bool_to_string (gboolean self) {
	gchar* result = NULL;
#line 37 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (self) {
#line 557 "fileHelper.c"
		gchar* _tmp0_ = NULL;
#line 38 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp0_ = g_strdup ("true");
#line 38 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		result = _tmp0_;
#line 38 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		return result;
#line 565 "fileHelper.c"
	} else {
		gchar* _tmp1_ = NULL;
#line 40 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp1_ = g_strdup ("false");
#line 40 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		result = _tmp1_;
#line 40 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		return result;
#line 574 "fileHelper.c"
	}
}


gboolean termites_file_helper_is_acceptable_file (GDataInputStream* file_reader) {
	gboolean result = FALSE;
	gchar* line_in_file = NULL;
	gchar* _tmp0_ = NULL;
	GDataInputStream* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar** application_line = NULL;
	const gchar* _tmp4_ = NULL;
	gchar** _tmp5_ = NULL;
	gchar** _tmp6_ = NULL;
	gint application_line_length1 = 0;
	gint _application_line_size_ = 0;
	gboolean application_okay = FALSE;
	gchar** _tmp7_ = NULL;
	gint _tmp7__length1 = 0;
	const gchar* _tmp8_ = NULL;
	gboolean version_okay = FALSE;
	gchar** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	const gchar* _tmp10_ = NULL;
	gboolean _tmp11_ = FALSE;
	FILE* _tmp12_ = NULL;
	gboolean _tmp13_ = FALSE;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gboolean _tmp16_ = FALSE;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gboolean _tmp19_ = FALSE;
	gboolean _tmp20_ = FALSE;
	GError * _inner_error_ = NULL;
#line 96 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	g_return_val_if_fail (file_reader != NULL, FALSE);
#line 98 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp1_ = file_reader;
#line 98 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp2_ = g_data_input_stream_read_line (_tmp1_, NULL, NULL, &_inner_error_);
#line 98 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp0_ = _tmp2_;
#line 98 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 98 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_g_free0 (line_in_file);
#line 98 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 98 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		g_clear_error (&_inner_error_);
#line 98 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		return FALSE;
#line 629 "fileHelper.c"
	}
#line 98 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp3_ = _tmp0_;
#line 98 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp0_ = NULL;
#line 98 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_g_free0 (line_in_file);
#line 98 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	line_in_file = _tmp3_;
#line 100 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp4_ = line_in_file;
#line 100 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp6_ = _tmp5_ = g_strsplit (_tmp4_, ":", 0);
#line 100 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	application_line = _tmp6_;
#line 100 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	application_line_length1 = _vala_array_length (_tmp5_);
#line 100 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_application_line_size_ = application_line_length1;
#line 102 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp7_ = application_line;
#line 102 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp7__length1 = application_line_length1;
#line 102 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp8_ = _tmp7_[0];
#line 102 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	application_okay = g_strcmp0 (_tmp8_, TERMITES_APPLICATION_APPLICATION_NAME) == 0;
#line 103 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp9_ = application_line;
#line 103 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp9__length1 = application_line_length1;
#line 103 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp10_ = _tmp9_[1];
#line 103 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp11_ = termites_application_is_compatible_version (_tmp10_);
#line 103 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	version_okay = _tmp11_;
#line 105 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp12_ = stdout;
#line 105 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp13_ = application_okay;
#line 105 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp14_ = bool_to_string (_tmp13_);
#line 105 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp15_ = _tmp14_;
#line 105 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp16_ = version_okay;
#line 105 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp17_ = bool_to_string (_tmp16_);
#line 105 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp18_ = _tmp17_;
#line 105 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	fprintf (_tmp12_, "Application Okay? : %s \nVersion Okay? : %s \n", _tmp15_, _tmp18_);
#line 105 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_g_free0 (_tmp18_);
#line 105 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_g_free0 (_tmp15_);
#line 107 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_tmp20_ = version_okay;
#line 107 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	if (_tmp20_) {
#line 691 "fileHelper.c"
		gboolean _tmp21_ = FALSE;
#line 107 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_tmp21_ = application_okay;
#line 107 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_tmp19_ = _tmp21_;
#line 697 "fileHelper.c"
	} else {
#line 107 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
		_tmp19_ = FALSE;
#line 701 "fileHelper.c"
	}
#line 107 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	result = _tmp19_;
#line 107 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	application_line = (_vala_array_free (application_line, application_line_length1, (GDestroyNotify) g_free), NULL);
#line 107 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_g_free0 (_tmp0_);
#line 107 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	_g_free0 (line_in_file);
#line 107 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	return result;
#line 713 "fileHelper.c"
}


TermitesFileHelper* termites_file_helper_construct (GType object_type) {
	TermitesFileHelper * self = NULL;
#line 32 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	self = (TermitesFileHelper*) g_object_new (object_type, NULL);
#line 32 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	return self;
#line 723 "fileHelper.c"
}


TermitesFileHelper* termites_file_helper_new (void) {
#line 32 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	return termites_file_helper_construct (TERMITES_TYPE_FILE_HELPER);
#line 730 "fileHelper.c"
}


static void termites_file_helper_class_init (TermitesFileHelperClass * klass) {
#line 32 "/home/vincent/Source/Vala/Termites/src/fileHelper.vala"
	termites_file_helper_parent_class = g_type_class_peek_parent (klass);
#line 737 "fileHelper.c"
}


static void termites_file_helper_instance_init (TermitesFileHelper * self) {
}


GType termites_file_helper_get_type (void) {
	static volatile gsize termites_file_helper_type_id__volatile = 0;
	if (g_once_init_enter (&termites_file_helper_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TermitesFileHelperClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) termites_file_helper_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TermitesFileHelper), 0, (GInstanceInitFunc) termites_file_helper_instance_init, NULL };
		GType termites_file_helper_type_id;
		termites_file_helper_type_id = g_type_register_static (G_TYPE_OBJECT, "TermitesFileHelper", &g_define_type_info, 0);
		g_once_init_leave (&termites_file_helper_type_id__volatile, termites_file_helper_type_id);
	}
	return termites_file_helper_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



