/* node.c generated by valac 0.28.1, the Vala compiler
 * generated from node.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * node.vala
 The MIT License (MIT)

 Copyright (c) 2015 Vinibo

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define TERMITES_TYPE_TERMITE_NODE (termites_termite_node_get_type ())
#define TERMITES_TERMITE_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNode))
#define TERMITES_TERMITE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNodeClass))
#define TERMITES_IS_TERMITE_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_TERMITE_NODE))
#define TERMITES_IS_TERMITE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_TERMITE_NODE))
#define TERMITES_TERMITE_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNodeClass))

typedef struct _TermitesTermiteNode TermitesTermiteNode;
typedef struct _TermitesTermiteNodeClass TermitesTermiteNodeClass;
typedef struct _TermitesTermiteNodePrivate TermitesTermiteNodePrivate;

#define TERMITES_TYPE_PROTOCOL (termites_protocol_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

struct _TermitesTermiteNode {
	GObject parent_instance;
	TermitesTermiteNodePrivate * priv;
};

struct _TermitesTermiteNodeClass {
	GObjectClass parent_class;
};

typedef enum  {
	TERMITES_PROTOCOL_NONE,
	TERMITES_PROTOCOL_SSH,
	TERMITES_PROTOCOL_TELNET,
	TERMITES_PROTOCOL_SERIAL,
	TERMITES_PROTOCOL_VNC,
	TERMITES_PROTOCOL_RDP
} TermitesProtocol;

struct _TermitesTermiteNodePrivate {
	gint _id;
	gchar* _name;
	gchar* _host;
	gchar* _port;
	gchar* _username;
	TermitesProtocol _protocol;
};


static gpointer termites_termite_node_parent_class = NULL;

GType termites_termite_node_get_type (void) G_GNUC_CONST;
GType termites_protocol_get_type (void) G_GNUC_CONST;
#define TERMITES_TERMITE_NODE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNodePrivate))
enum  {
	TERMITES_TERMITE_NODE_DUMMY_PROPERTY,
	TERMITES_TERMITE_NODE_ID,
	TERMITES_TERMITE_NODE_NAME,
	TERMITES_TERMITE_NODE_HOST,
	TERMITES_TERMITE_NODE_PORT,
	TERMITES_TERMITE_NODE_USERNAME,
	TERMITES_TERMITE_NODE_PROTOCOL
};
TermitesTermiteNode* termites_termite_node_new (gint p_id, const gchar* p_name, const gchar* p_host, const gchar* p_port, const gchar* p_username, TermitesProtocol p_protocol);
TermitesTermiteNode* termites_termite_node_construct (GType object_type, gint p_id, const gchar* p_name, const gchar* p_host, const gchar* p_port, const gchar* p_username, TermitesProtocol p_protocol);
void termites_termite_node_set_id (TermitesTermiteNode* self, gint value);
void termites_termite_node_set_name (TermitesTermiteNode* self, const gchar* value);
void termites_termite_node_set_host (TermitesTermiteNode* self, const gchar* value);
void termites_termite_node_set_port (TermitesTermiteNode* self, const gchar* value);
void termites_termite_node_set_username (TermitesTermiteNode* self, const gchar* value);
void termites_termite_node_set_protocol (TermitesTermiteNode* self, TermitesProtocol value);
TermitesTermiteNode* termites_termite_node_new_empty (void);
TermitesTermiteNode* termites_termite_node_construct_empty (GType object_type);
TermitesTermiteNode* termites_termite_node_new_copy (TermitesTermiteNode* p_original_instance);
TermitesTermiteNode* termites_termite_node_construct_copy (GType object_type, TermitesTermiteNode* p_original_instance);
gint termites_termite_node_get_id (TermitesTermiteNode* self);
const gchar* termites_termite_node_get_name (TermitesTermiteNode* self);
const gchar* termites_termite_node_get_host (TermitesTermiteNode* self);
const gchar* termites_termite_node_get_port (TermitesTermiteNode* self);
const gchar* termites_termite_node_get_username (TermitesTermiteNode* self);
TermitesTermiteNode* termites_termite_node_new_as_logical_node (const gchar* name);
TermitesTermiteNode* termites_termite_node_construct_as_logical_node (GType object_type, const gchar* name);
gchar* termites_termite_node_get_connection_string (TermitesTermiteNode* self);
gchar* termites_termite_node_serialize (TermitesTermiteNode* self);
TermitesProtocol termites_termite_node_get_protocol (TermitesTermiteNode* self);
static void termites_termite_node_finalize (GObject* obj);
static void _vala_termites_termite_node_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_termites_termite_node_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


TermitesTermiteNode* termites_termite_node_construct (GType object_type, gint p_id, const gchar* p_name, const gchar* p_host, const gchar* p_port, const gchar* p_username, TermitesProtocol p_protocol) {
	TermitesTermiteNode * self = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	TermitesProtocol _tmp5_ = 0;
#line 43 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (p_name != NULL, NULL);
#line 43 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (p_host != NULL, NULL);
#line 43 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (p_port != NULL, NULL);
#line 43 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (p_username != NULL, NULL);
#line 43 "/home/vincent/Source/Vala/Termites/src/node.vala"
	self = (TermitesTermiteNode*) g_object_new (object_type, NULL);
#line 44 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = p_id;
#line 44 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_set_id (self, _tmp0_);
#line 45 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp1_ = p_name;
#line 45 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_set_name (self, _tmp1_);
#line 46 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp2_ = p_host;
#line 46 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_set_host (self, _tmp2_);
#line 47 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp3_ = p_port;
#line 47 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_set_port (self, _tmp3_);
#line 48 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp4_ = p_username;
#line 48 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_set_username (self, _tmp4_);
#line 49 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp5_ = p_protocol;
#line 49 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_set_protocol (self, _tmp5_);
#line 43 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return self;
#line 164 "node.c"
}


TermitesTermiteNode* termites_termite_node_new (gint p_id, const gchar* p_name, const gchar* p_host, const gchar* p_port, const gchar* p_username, TermitesProtocol p_protocol) {
#line 43 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return termites_termite_node_construct (TERMITES_TYPE_TERMITE_NODE, p_id, p_name, p_host, p_port, p_username, p_protocol);
#line 171 "node.c"
}


TermitesTermiteNode* termites_termite_node_construct_empty (GType object_type) {
	TermitesTermiteNode * self = NULL;
#line 52 "/home/vincent/Source/Vala/Termites/src/node.vala"
	self = (TermitesTermiteNode*) g_object_new (object_type, NULL);
#line 52 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return self;
#line 181 "node.c"
}


TermitesTermiteNode* termites_termite_node_new_empty (void) {
#line 52 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return termites_termite_node_construct_empty (TERMITES_TYPE_TERMITE_NODE);
#line 188 "node.c"
}


TermitesTermiteNode* termites_termite_node_construct_copy (GType object_type, TermitesTermiteNode* p_original_instance) {
	TermitesTermiteNode * self = NULL;
	TermitesTermiteNode* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	TermitesTermiteNode* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	TermitesTermiteNode* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	TermitesTermiteNode* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	TermitesTermiteNode* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
#line 54 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (p_original_instance != NULL, NULL);
#line 54 "/home/vincent/Source/Vala/Termites/src/node.vala"
	self = (TermitesTermiteNode*) g_object_new (object_type, NULL);
#line 55 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = p_original_instance;
#line 55 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp1_ = _tmp0_->priv->_id;
#line 55 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_set_id (self, _tmp1_);
#line 56 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp2_ = p_original_instance;
#line 56 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp3_ = _tmp2_->priv->_name;
#line 56 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_set_name (self, _tmp3_);
#line 57 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp4_ = p_original_instance;
#line 57 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp5_ = _tmp4_->priv->_host;
#line 57 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_set_host (self, _tmp5_);
#line 58 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp6_ = p_original_instance;
#line 58 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp7_ = _tmp6_->priv->_port;
#line 58 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_set_port (self, _tmp7_);
#line 59 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp8_ = p_original_instance;
#line 59 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp9_ = _tmp8_->priv->_username;
#line 59 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_set_username (self, _tmp9_);
#line 54 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return self;
#line 240 "node.c"
}


TermitesTermiteNode* termites_termite_node_new_copy (TermitesTermiteNode* p_original_instance) {
#line 54 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return termites_termite_node_construct_copy (TERMITES_TYPE_TERMITE_NODE, p_original_instance);
#line 247 "node.c"
}


TermitesTermiteNode* termites_termite_node_construct_as_logical_node (GType object_type, const gchar* name) {
	TermitesTermiteNode * self = NULL;
	const gchar* _tmp0_ = NULL;
#line 62 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 62 "/home/vincent/Source/Vala/Termites/src/node.vala"
	self = (TermitesTermiteNode*) g_object_new (object_type, NULL);
#line 63 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = name;
#line 63 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_set_name (self, _tmp0_);
#line 62 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return self;
#line 264 "node.c"
}


TermitesTermiteNode* termites_termite_node_new_as_logical_node (const gchar* name) {
#line 62 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return termites_termite_node_construct_as_logical_node (TERMITES_TYPE_TERMITE_NODE, name);
#line 271 "node.c"
}


gchar* termites_termite_node_get_connection_string (TermitesTermiteNode* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
#line 66 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 67 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = self->priv->_username;
#line 67 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp1_ = g_strconcat (_tmp0_, "@", NULL);
#line 67 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp2_ = _tmp1_;
#line 67 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp3_ = self->priv->_host;
#line 67 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp4_ = g_strconcat (_tmp2_, _tmp3_, NULL);
#line 67 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp5_ = _tmp4_;
#line 67 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (_tmp2_);
#line 67 "/home/vincent/Source/Vala/Termites/src/node.vala"
	result = _tmp5_;
#line 67 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return result;
#line 303 "node.c"
}


gchar* termites_termite_node_serialize (TermitesTermiteNode* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
#line 70 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = self->priv->_name;
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp1_ = g_strconcat (_tmp0_, ",", NULL);
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp2_ = _tmp1_;
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp3_ = self->priv->_host;
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp4_ = g_strconcat (_tmp2_, _tmp3_, NULL);
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp5_ = _tmp4_;
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp6_ = g_strconcat (_tmp5_, ",", NULL);
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp7_ = _tmp6_;
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp8_ = self->priv->_port;
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp9_ = g_strconcat (_tmp7_, _tmp8_, NULL);
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp10_ = _tmp9_;
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp11_ = g_strconcat (_tmp10_, ",", NULL);
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp12_ = _tmp11_;
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp13_ = self->priv->_username;
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp14_ = g_strconcat (_tmp12_, _tmp13_, NULL);
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp15_ = _tmp14_;
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (_tmp12_);
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (_tmp10_);
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (_tmp7_);
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (_tmp5_);
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (_tmp2_);
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	result = _tmp15_;
#line 71 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return result;
#line 373 "node.c"
}


gint termites_termite_node_get_id (TermitesTermiteNode* self) {
	gint result;
	gint _tmp0_ = 0;
#line 36 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 36 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = self->priv->_id;
#line 36 "/home/vincent/Source/Vala/Termites/src/node.vala"
	result = _tmp0_;
#line 36 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return result;
#line 388 "node.c"
}


void termites_termite_node_set_id (TermitesTermiteNode* self, gint value) {
	gint _tmp0_ = 0;
#line 36 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_if_fail (self != NULL);
#line 36 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = value;
#line 36 "/home/vincent/Source/Vala/Termites/src/node.vala"
	self->priv->_id = _tmp0_;
#line 36 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_object_notify ((GObject *) self, "id");
#line 402 "node.c"
}


const gchar* termites_termite_node_get_name (TermitesTermiteNode* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 37 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 37 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = self->priv->_name;
#line 37 "/home/vincent/Source/Vala/Termites/src/node.vala"
	result = _tmp0_;
#line 37 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return result;
#line 417 "node.c"
}


void termites_termite_node_set_name (TermitesTermiteNode* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 37 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_if_fail (self != NULL);
#line 37 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = value;
#line 37 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 37 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (self->priv->_name);
#line 37 "/home/vincent/Source/Vala/Termites/src/node.vala"
	self->priv->_name = _tmp1_;
#line 37 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_object_notify ((GObject *) self, "name");
#line 436 "node.c"
}


const gchar* termites_termite_node_get_host (TermitesTermiteNode* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 38 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 38 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = self->priv->_host;
#line 38 "/home/vincent/Source/Vala/Termites/src/node.vala"
	result = _tmp0_;
#line 38 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return result;
#line 451 "node.c"
}


void termites_termite_node_set_host (TermitesTermiteNode* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 38 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_if_fail (self != NULL);
#line 38 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = value;
#line 38 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 38 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (self->priv->_host);
#line 38 "/home/vincent/Source/Vala/Termites/src/node.vala"
	self->priv->_host = _tmp1_;
#line 38 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_object_notify ((GObject *) self, "host");
#line 470 "node.c"
}


const gchar* termites_termite_node_get_port (TermitesTermiteNode* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 39 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 39 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = self->priv->_port;
#line 39 "/home/vincent/Source/Vala/Termites/src/node.vala"
	result = _tmp0_;
#line 39 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return result;
#line 485 "node.c"
}


void termites_termite_node_set_port (TermitesTermiteNode* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 39 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_if_fail (self != NULL);
#line 39 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = value;
#line 39 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 39 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (self->priv->_port);
#line 39 "/home/vincent/Source/Vala/Termites/src/node.vala"
	self->priv->_port = _tmp1_;
#line 39 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_object_notify ((GObject *) self, "port");
#line 504 "node.c"
}


const gchar* termites_termite_node_get_username (TermitesTermiteNode* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 40 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 40 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = self->priv->_username;
#line 40 "/home/vincent/Source/Vala/Termites/src/node.vala"
	result = _tmp0_;
#line 40 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return result;
#line 519 "node.c"
}


void termites_termite_node_set_username (TermitesTermiteNode* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 40 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_if_fail (self != NULL);
#line 40 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = value;
#line 40 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 40 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (self->priv->_username);
#line 40 "/home/vincent/Source/Vala/Termites/src/node.vala"
	self->priv->_username = _tmp1_;
#line 40 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_object_notify ((GObject *) self, "username");
#line 538 "node.c"
}


TermitesProtocol termites_termite_node_get_protocol (TermitesTermiteNode* self) {
	TermitesProtocol result;
	TermitesProtocol _tmp0_ = 0;
#line 41 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 41 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = self->priv->_protocol;
#line 41 "/home/vincent/Source/Vala/Termites/src/node.vala"
	result = _tmp0_;
#line 41 "/home/vincent/Source/Vala/Termites/src/node.vala"
	return result;
#line 553 "node.c"
}


void termites_termite_node_set_protocol (TermitesTermiteNode* self, TermitesProtocol value) {
	TermitesProtocol _tmp0_ = 0;
#line 41 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_return_if_fail (self != NULL);
#line 41 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_tmp0_ = value;
#line 41 "/home/vincent/Source/Vala/Termites/src/node.vala"
	self->priv->_protocol = _tmp0_;
#line 41 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_object_notify ((GObject *) self, "protocol");
#line 567 "node.c"
}


static void termites_termite_node_class_init (TermitesTermiteNodeClass * klass) {
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	termites_termite_node_parent_class = g_type_class_peek_parent (klass);
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_type_class_add_private (klass, sizeof (TermitesTermiteNodePrivate));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_termites_termite_node_get_property;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_termites_termite_node_set_property;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	G_OBJECT_CLASS (klass)->finalize = termites_termite_node_finalize;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), TERMITES_TERMITE_NODE_ID, g_param_spec_int ("id", "id", "id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), TERMITES_TERMITE_NODE_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), TERMITES_TERMITE_NODE_HOST, g_param_spec_string ("host", "host", "host", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), TERMITES_TERMITE_NODE_PORT, g_param_spec_string ("port", "port", "port", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), TERMITES_TERMITE_NODE_USERNAME, g_param_spec_string ("username", "username", "username", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), TERMITES_TERMITE_NODE_PROTOCOL, g_param_spec_enum ("protocol", "protocol", "protocol", TERMITES_TYPE_PROTOCOL, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 594 "node.c"
}


static void termites_termite_node_instance_init (TermitesTermiteNode * self) {
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	self->priv = TERMITES_TERMITE_NODE_GET_PRIVATE (self);
#line 601 "node.c"
}


static void termites_termite_node_finalize (GObject* obj) {
	TermitesTermiteNode * self;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNode);
#line 37 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (self->priv->_name);
#line 38 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (self->priv->_host);
#line 39 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (self->priv->_port);
#line 40 "/home/vincent/Source/Vala/Termites/src/node.vala"
	_g_free0 (self->priv->_username);
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	G_OBJECT_CLASS (termites_termite_node_parent_class)->finalize (obj);
#line 619 "node.c"
}


GType termites_termite_node_get_type (void) {
	static volatile gsize termites_termite_node_type_id__volatile = 0;
	if (g_once_init_enter (&termites_termite_node_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TermitesTermiteNodeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) termites_termite_node_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TermitesTermiteNode), 0, (GInstanceInitFunc) termites_termite_node_instance_init, NULL };
		GType termites_termite_node_type_id;
		termites_termite_node_type_id = g_type_register_static (G_TYPE_OBJECT, "TermitesTermiteNode", &g_define_type_info, 0);
		g_once_init_leave (&termites_termite_node_type_id__volatile, termites_termite_node_type_id);
	}
	return termites_termite_node_type_id__volatile;
}


static void _vala_termites_termite_node_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	TermitesTermiteNode * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNode);
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	switch (property_id) {
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		case TERMITES_TERMITE_NODE_ID:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		g_value_set_int (value, termites_termite_node_get_id (self));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		case TERMITES_TERMITE_NODE_NAME:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		g_value_set_string (value, termites_termite_node_get_name (self));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		case TERMITES_TERMITE_NODE_HOST:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		g_value_set_string (value, termites_termite_node_get_host (self));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		case TERMITES_TERMITE_NODE_PORT:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		g_value_set_string (value, termites_termite_node_get_port (self));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		case TERMITES_TERMITE_NODE_USERNAME:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		g_value_set_string (value, termites_termite_node_get_username (self));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		case TERMITES_TERMITE_NODE_PROTOCOL:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		g_value_set_enum (value, termites_termite_node_get_protocol (self));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 676 "node.c"
		default:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 682 "node.c"
	}
}


static void _vala_termites_termite_node_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	TermitesTermiteNode * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNode);
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
	switch (property_id) {
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		case TERMITES_TERMITE_NODE_ID:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		termites_termite_node_set_id (self, g_value_get_int (value));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		case TERMITES_TERMITE_NODE_NAME:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		termites_termite_node_set_name (self, g_value_get_string (value));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		case TERMITES_TERMITE_NODE_HOST:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		termites_termite_node_set_host (self, g_value_get_string (value));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		case TERMITES_TERMITE_NODE_PORT:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		termites_termite_node_set_port (self, g_value_get_string (value));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		case TERMITES_TERMITE_NODE_USERNAME:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		termites_termite_node_set_username (self, g_value_get_string (value));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		case TERMITES_TERMITE_NODE_PROTOCOL:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		termites_termite_node_set_protocol (self, g_value_get_enum (value));
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 728 "node.c"
		default:
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 32 "/home/vincent/Source/Vala/Termites/src/node.vala"
		break;
#line 734 "node.c"
	}
}



