/* nodeProperties.c generated by valac 0.28.1, the Vala compiler
 * generated from nodeProperties.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * nodeProperties.vala
 The MIT License (MIT)

 Copyright (c) 2015 Vinibo

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <gio/gio.h>


#define TERMITES_TYPE_NODE_PROPERTIES (termites_node_properties_get_type ())
#define TERMITES_NODE_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_NODE_PROPERTIES, TermitesNodeProperties))
#define TERMITES_NODE_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_NODE_PROPERTIES, TermitesNodePropertiesClass))
#define TERMITES_IS_NODE_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_NODE_PROPERTIES))
#define TERMITES_IS_NODE_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_NODE_PROPERTIES))
#define TERMITES_NODE_PROPERTIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_NODE_PROPERTIES, TermitesNodePropertiesClass))

typedef struct _TermitesNodeProperties TermitesNodeProperties;
typedef struct _TermitesNodePropertiesClass TermitesNodePropertiesClass;
typedef struct _TermitesNodePropertiesPrivate TermitesNodePropertiesPrivate;

#define TERMITES_TYPE_TERMITE_NODE (termites_termite_node_get_type ())
#define TERMITES_TERMITE_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNode))
#define TERMITES_TERMITE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNodeClass))
#define TERMITES_IS_TERMITE_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_TERMITE_NODE))
#define TERMITES_IS_TERMITE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_TERMITE_NODE))
#define TERMITES_TERMITE_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNodeClass))

typedef struct _TermitesTermiteNode TermitesTermiteNode;
typedef struct _TermitesTermiteNodeClass TermitesTermiteNodeClass;

#define TERMITES_TYPE_TERMITE_STORE (termites_termite_store_get_type ())
#define TERMITES_TERMITE_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStore))
#define TERMITES_TERMITE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStoreClass))
#define TERMITES_IS_TERMITE_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_TERMITE_STORE))
#define TERMITES_IS_TERMITE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_TERMITE_STORE))
#define TERMITES_TERMITE_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStoreClass))

typedef struct _TermitesTermiteStore TermitesTermiteStore;
typedef struct _TermitesTermiteStoreClass TermitesTermiteStoreClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) ((var == NULL) ? NULL : (var = (g_free (var), NULL)))

#define TERMITES_TYPE_PROTOCOL (termites_protocol_get_type ())
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _TermitesNodeProperties {
	GtkDialog parent_instance;
	TermitesNodePropertiesPrivate * priv;
};

struct _TermitesNodePropertiesClass {
	GtkDialogClass parent_class;
};

struct _TermitesNodePropertiesPrivate {
	GtkEntry* txtNodeName;
	GtkEntry* txtHostname;
	GtkEntry* txtPort;
	GtkEntry* txtUsername;
	GtkComboBox* cbProtocol;
	TermitesTermiteNode* node;
	TermitesTermiteStore* m_tree_view;
	GtkTreeIter* node_emplacement;
};

typedef enum  {
	TERMITES_PROTOCOL_NONE,
	TERMITES_PROTOCOL_SSH,
	TERMITES_PROTOCOL_TELNET,
	TERMITES_PROTOCOL_SERIAL,
	TERMITES_PROTOCOL_VNC,
	TERMITES_PROTOCOL_RDP
} TermitesProtocol;


static gpointer termites_node_properties_parent_class = NULL;

GType termites_node_properties_get_type (void) G_GNUC_CONST;
GType termites_termite_node_get_type (void) G_GNUC_CONST;
GType termites_termite_store_get_type (void) G_GNUC_CONST;
#define TERMITES_NODE_PROPERTIES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TERMITES_TYPE_NODE_PROPERTIES, TermitesNodePropertiesPrivate))
enum  {
	TERMITES_NODE_PROPERTIES_DUMMY_PROPERTY
};
TermitesNodeProperties* termites_node_properties_new_edit (TermitesTermiteStore** termites, GtkTreeSelection* selected_node);
TermitesNodeProperties* termites_node_properties_construct_edit (GType object_type, TermitesTermiteStore** termites, GtkTreeSelection* selected_node);
static void termites_node_properties_init_protocols (TermitesNodeProperties* self);
static GtkTreeIter* _gtk_tree_iter_dup (GtkTreeIter* self);
const gchar* termites_termite_node_get_name (TermitesTermiteNode* self);
const gchar* termites_termite_node_get_host (TermitesTermiteNode* self);
const gchar* termites_termite_node_get_port (TermitesTermiteNode* self);
const gchar* termites_termite_node_get_username (TermitesTermiteNode* self);
GType termites_protocol_get_type (void) G_GNUC_CONST;
TermitesProtocol termites_termite_node_get_protocol (TermitesTermiteNode* self);
TermitesNodeProperties* termites_node_properties_new_new (TermitesTermiteStore** termites);
TermitesNodeProperties* termites_node_properties_construct_new (GType object_type, TermitesTermiteStore** termites);
void termites_node_properties_show_window (TermitesNodeProperties* self, GtkWindow* p_parent_window);
void termites_node_properties_cancel (TermitesNodeProperties* self);
static void _termites_node_properties_cancel_gtk_button_clicked (GtkButton* _sender, gpointer self);
void termites_node_properties_save_node (TermitesNodeProperties* self);
static gboolean termites_node_properties_validate_form (TermitesNodeProperties* self);
TermitesTermiteNode* termites_termite_node_new_empty (void);
TermitesTermiteNode* termites_termite_node_construct_empty (GType object_type);
void termites_termite_node_set_name (TermitesTermiteNode* self, const gchar* value);
void termites_termite_node_set_host (TermitesTermiteNode* self, const gchar* value);
void termites_termite_node_set_port (TermitesTermiteNode* self, const gchar* value);
void termites_termite_node_set_username (TermitesTermiteNode* self, const gchar* value);
TermitesProtocol termites_protocol_get (gint p_proto);
void termites_termite_node_set_protocol (TermitesTermiteNode* self, TermitesProtocol value);
void termites_termite_store_add_node (TermitesTermiteStore* self, TermitesTermiteNode* node, GtkTreeIter* position, GtkTreeIter* position_inserted);
void termites_termite_store_update_node (TermitesTermiteStore* self, TermitesTermiteNode* node, GtkTreeIter* position);
static void _termites_node_properties_save_node_gtk_button_clicked (GtkButton* _sender, gpointer self);
TermitesProtocol* termites_protocol_all (int* result_length1);
gchar* termites_protocol_to_string (TermitesProtocol self);
static gboolean termites_node_properties_is_service_reachable (TermitesNodeProperties* self);
TermitesNodeProperties* termites_node_properties_new (void);
TermitesNodeProperties* termites_node_properties_construct (GType object_type);
static void termites_node_properties_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
#line 60 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	return self ? g_object_ref (self) : NULL;
#line 154 "nodeProperties.c"
}


static GtkTreeIter* _gtk_tree_iter_dup (GtkTreeIter* self) {
	GtkTreeIter* dup;
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	dup = g_new0 (GtkTreeIter, 1);
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	memcpy (dup, self, sizeof (GtkTreeIter));
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	return dup;
#line 166 "nodeProperties.c"
}


static gpointer __gtk_tree_iter_dup0 (gpointer self) {
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	return self ? _gtk_tree_iter_dup (self) : NULL;
#line 173 "nodeProperties.c"
}


TermitesNodeProperties* termites_node_properties_construct_edit (GType object_type, TermitesTermiteStore** termites, GtkTreeSelection* selected_node) {
	TermitesNodeProperties * self = NULL;
	GtkTreeModel* model = NULL;
	GValue node_from_tree = {0};
	TermitesTermiteStore* _tmp0_ = NULL;
	TermitesTermiteStore* _tmp1_ = NULL;
	GtkTreeSelection* _tmp2_ = NULL;
	GtkTreeModel* _tmp3_ = NULL;
	GtkTreeIter _tmp4_ = {0};
	GtkTreeModel* _tmp5_ = NULL;
	GtkTreeIter _tmp6_ = {0};
	GtkTreeIter* _tmp7_ = NULL;
	GtkTreeIter* _tmp8_ = NULL;
	GtkTreeIter _tmp9_ = {0};
	GValue _tmp10_ = {0};
	GValue _tmp11_ = {0};
	TermitesTermiteNode* _tmp12_ = NULL;
	GtkEntry* _tmp13_ = NULL;
	TermitesTermiteNode* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	GtkEntry* _tmp17_ = NULL;
	TermitesTermiteNode* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	GtkEntry* _tmp21_ = NULL;
	TermitesTermiteNode* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	const gchar* _tmp24_ = NULL;
	GtkEntry* _tmp25_ = NULL;
	TermitesTermiteNode* _tmp26_ = NULL;
	const gchar* _tmp27_ = NULL;
	const gchar* _tmp28_ = NULL;
	GtkComboBox* _tmp29_ = NULL;
	TermitesTermiteNode* _tmp30_ = NULL;
	TermitesProtocol _tmp31_ = 0;
	TermitesProtocol _tmp32_ = 0;
#line 55 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_return_val_if_fail (*termites != NULL, NULL);
#line 55 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_return_val_if_fail (selected_node != NULL, NULL);
#line 55 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self = (TermitesNodeProperties*) g_object_new (object_type, NULL);
#line 59 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	termites_node_properties_init_protocols (self);
#line 60 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp0_ = *termites;
#line 60 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 60 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (self->priv->m_tree_view);
#line 60 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self->priv->m_tree_view = _tmp1_;
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp2_ = selected_node;
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_tree_selection_get_selected (_tmp2_, &_tmp3_, &_tmp4_);
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (model);
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp5_ = _g_object_ref0 (_tmp3_);
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	model = _tmp5_;
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_free0 (self->priv->node_emplacement);
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp6_ = _tmp4_;
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp7_ = __gtk_tree_iter_dup0 (&_tmp6_);
#line 63 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self->priv->node_emplacement = _tmp7_;
#line 65 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp8_ = self->priv->node_emplacement;
#line 65 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp9_ = *_tmp8_;
#line 65 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_tree_model_get_value (model, &_tmp9_, 1, &_tmp10_);
#line 65 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	G_IS_VALUE (&node_from_tree) ? (g_value_unset (&node_from_tree), NULL) : NULL;
#line 65 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	node_from_tree = _tmp10_;
#line 66 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp11_ = node_from_tree;
#line 66 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp12_ = _g_object_ref0 (g_value_get_object (&_tmp11_));
#line 66 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (self->priv->node);
#line 66 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self->priv->node = _tmp12_;
#line 69 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp13_ = self->priv->txtNodeName;
#line 69 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp14_ = self->priv->node;
#line 69 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp15_ = termites_termite_node_get_name (_tmp14_);
#line 69 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp16_ = _tmp15_;
#line 69 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_entry_set_text (_tmp13_, _tmp16_);
#line 70 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp17_ = self->priv->txtHostname;
#line 70 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp18_ = self->priv->node;
#line 70 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp19_ = termites_termite_node_get_host (_tmp18_);
#line 70 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp20_ = _tmp19_;
#line 70 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_entry_set_text (_tmp17_, _tmp20_);
#line 71 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp21_ = self->priv->txtPort;
#line 71 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp22_ = self->priv->node;
#line 71 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp23_ = termites_termite_node_get_port (_tmp22_);
#line 71 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp24_ = _tmp23_;
#line 71 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_entry_set_text (_tmp21_, _tmp24_);
#line 72 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp25_ = self->priv->txtUsername;
#line 72 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp26_ = self->priv->node;
#line 72 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp27_ = termites_termite_node_get_username (_tmp26_);
#line 72 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp28_ = _tmp27_;
#line 72 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_entry_set_text (_tmp25_, _tmp28_);
#line 73 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp29_ = self->priv->cbProtocol;
#line 73 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp30_ = self->priv->node;
#line 73 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp31_ = termites_termite_node_get_protocol (_tmp30_);
#line 73 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp32_ = _tmp31_;
#line 73 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_combo_box_set_active (_tmp29_, (gint) _tmp32_);
#line 55 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	G_IS_VALUE (&node_from_tree) ? (g_value_unset (&node_from_tree), NULL) : NULL;
#line 55 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (model);
#line 55 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	return self;
#line 322 "nodeProperties.c"
}


TermitesNodeProperties* termites_node_properties_new_edit (TermitesTermiteStore** termites, GtkTreeSelection* selected_node) {
#line 55 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	return termites_node_properties_construct_edit (TERMITES_TYPE_NODE_PROPERTIES, termites, selected_node);
#line 329 "nodeProperties.c"
}


TermitesNodeProperties* termites_node_properties_construct_new (GType object_type, TermitesTermiteStore** termites) {
	TermitesNodeProperties * self = NULL;
	TermitesTermiteStore* _tmp0_ = NULL;
	TermitesTermiteStore* _tmp1_ = NULL;
#line 76 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_return_val_if_fail (*termites != NULL, NULL);
#line 76 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self = (TermitesNodeProperties*) g_object_new (object_type, NULL);
#line 78 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	termites_node_properties_init_protocols (self);
#line 79 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp0_ = *termites;
#line 79 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 79 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (self->priv->m_tree_view);
#line 79 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self->priv->m_tree_view = _tmp1_;
#line 76 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	return self;
#line 353 "nodeProperties.c"
}


TermitesNodeProperties* termites_node_properties_new_new (TermitesTermiteStore** termites) {
#line 76 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	return termites_node_properties_construct_new (TERMITES_TYPE_NODE_PROPERTIES, termites);
#line 360 "nodeProperties.c"
}


void termites_node_properties_show_window (TermitesNodeProperties* self, GtkWindow* p_parent_window) {
	GtkWindow* _tmp0_ = NULL;
#line 82 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_return_if_fail (self != NULL);
#line 82 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_return_if_fail (p_parent_window != NULL);
#line 84 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp0_ = p_parent_window;
#line 84 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_window_set_transient_for ((GtkWindow*) self, _tmp0_);
#line 85 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 376 "nodeProperties.c"
}


void termites_node_properties_cancel (TermitesNodeProperties* self) {
#line 89 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_return_if_fail (self != NULL);
#line 90 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 385 "nodeProperties.c"
}


static void _termites_node_properties_cancel_gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	termites_node_properties_cancel ((TermitesNodeProperties*) self);
#line 392 "nodeProperties.c"
}


void termites_node_properties_save_node (TermitesNodeProperties* self) {
	gboolean _tmp0_ = FALSE;
#line 94 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_return_if_fail (self != NULL);
#line 101 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp0_ = termites_node_properties_validate_form (self);
#line 101 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	if (_tmp0_) {
#line 404 "nodeProperties.c"
		GtkTreeIter wasteland = {0};
		GtkTreeIter* _tmp1_ = NULL;
		TermitesTermiteNode* _tmp3_ = NULL;
		GtkEntry* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		TermitesTermiteNode* _tmp6_ = NULL;
		GtkEntry* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		TermitesTermiteNode* _tmp9_ = NULL;
		GtkEntry* _tmp10_ = NULL;
		const gchar* _tmp11_ = NULL;
		TermitesTermiteNode* _tmp12_ = NULL;
		GtkEntry* _tmp13_ = NULL;
		const gchar* _tmp14_ = NULL;
		TermitesTermiteNode* _tmp15_ = NULL;
		GtkComboBox* _tmp16_ = NULL;
		gint _tmp17_ = 0;
		TermitesProtocol _tmp18_ = 0;
		GtkTreeIter* _tmp19_ = NULL;
#line 105 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp1_ = self->priv->node_emplacement;
#line 105 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		if (_tmp1_ == NULL) {
#line 428 "nodeProperties.c"
			TermitesTermiteNode* _tmp2_ = NULL;
#line 106 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			_tmp2_ = termites_termite_node_new_empty ();
#line 106 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			_g_object_unref0 (self->priv->node);
#line 106 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			self->priv->node = _tmp2_;
#line 436 "nodeProperties.c"
		}
#line 109 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp3_ = self->priv->node;
#line 109 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp4_ = self->priv->txtNodeName;
#line 109 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp5_ = gtk_entry_get_text (_tmp4_);
#line 109 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		termites_termite_node_set_name (_tmp3_, _tmp5_);
#line 110 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp6_ = self->priv->node;
#line 110 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp7_ = self->priv->txtHostname;
#line 110 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp8_ = gtk_entry_get_text (_tmp7_);
#line 110 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		termites_termite_node_set_host (_tmp6_, _tmp8_);
#line 111 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp9_ = self->priv->node;
#line 111 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp10_ = self->priv->txtPort;
#line 111 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp11_ = gtk_entry_get_text (_tmp10_);
#line 111 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		termites_termite_node_set_port (_tmp9_, _tmp11_);
#line 112 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp12_ = self->priv->node;
#line 112 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp13_ = self->priv->txtUsername;
#line 112 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp14_ = gtk_entry_get_text (_tmp13_);
#line 112 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		termites_termite_node_set_username (_tmp12_, _tmp14_);
#line 113 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp15_ = self->priv->node;
#line 113 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp16_ = self->priv->cbProtocol;
#line 113 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp17_ = gtk_combo_box_get_active (_tmp16_);
#line 113 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp18_ = termites_protocol_get (_tmp17_ + 1);
#line 113 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		termites_termite_node_set_protocol (_tmp15_, _tmp18_);
#line 117 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp19_ = self->priv->node_emplacement;
#line 117 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		if (_tmp19_ == NULL) {
#line 484 "nodeProperties.c"
			TermitesTermiteStore* _tmp20_ = NULL;
			TermitesTermiteNode* _tmp21_ = NULL;
			GtkTreeIter _tmp22_ = {0};
#line 118 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			_tmp20_ = self->priv->m_tree_view;
#line 118 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			_tmp21_ = self->priv->node;
#line 118 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			termites_termite_store_add_node (_tmp20_, _tmp21_, NULL, &_tmp22_);
#line 118 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			wasteland = _tmp22_;
#line 496 "nodeProperties.c"
		} else {
			TermitesTermiteStore* _tmp23_ = NULL;
			TermitesTermiteNode* _tmp24_ = NULL;
			GtkTreeIter* _tmp25_ = NULL;
			GtkTreeIter _tmp26_ = {0};
#line 120 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			_tmp23_ = self->priv->m_tree_view;
#line 120 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			_tmp24_ = self->priv->node;
#line 120 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			_tmp25_ = self->priv->node_emplacement;
#line 120 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			_tmp26_ = *_tmp25_;
#line 120 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			termites_termite_store_update_node (_tmp23_, _tmp24_, &_tmp26_);
#line 512 "nodeProperties.c"
		}
#line 124 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		g_signal_emit_by_name ((GtkDialog*) self, "close");
#line 516 "nodeProperties.c"
	}
}


static void _termites_node_properties_save_node_gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	termites_node_properties_save_node ((TermitesNodeProperties*) self);
#line 524 "nodeProperties.c"
}


static void termites_node_properties_init_protocols (TermitesNodeProperties* self) {
	GtkListStore* protoStore = NULL;
	GtkListStore* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	TermitesProtocol* _tmp2_ = NULL;
	GtkComboBox* _tmp10_ = NULL;
	GtkListStore* _tmp11_ = NULL;
	GtkCellRendererText* cell = NULL;
	GtkCellRendererText* _tmp12_ = NULL;
	GtkComboBox* _tmp13_ = NULL;
	GtkComboBox* _tmp14_ = NULL;
	GtkComboBox* _tmp15_ = NULL;
#line 128 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_return_if_fail (self != NULL);
#line 130 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp0_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
#line 130 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	protoStore = _tmp0_;
#line 131 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp2_ = termites_protocol_all (&_tmp1_);
#line 548 "nodeProperties.c"
	{
		TermitesProtocol* ptl_collection = NULL;
		gint ptl_collection_length1 = 0;
		gint _ptl_collection_size_ = 0;
		gint ptl_it = 0;
#line 131 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		ptl_collection = _tmp2_;
#line 131 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		ptl_collection_length1 = _tmp1_;
#line 131 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		for (ptl_it = 0; ptl_it < _tmp1_; ptl_it = ptl_it + 1) {
#line 560 "nodeProperties.c"
			TermitesProtocol ptl = 0;
#line 131 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
			ptl = ptl_collection[ptl_it];
#line 564 "nodeProperties.c"
			{
				GtkTreeIter iter = {0};
				GtkListStore* _tmp3_ = NULL;
				GtkTreeIter _tmp4_ = {0};
				GtkListStore* _tmp5_ = NULL;
				GtkTreeIter _tmp6_ = {0};
				TermitesProtocol _tmp7_ = 0;
				gchar* _tmp8_ = NULL;
				gchar* _tmp9_ = NULL;
#line 133 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
				_tmp3_ = protoStore;
#line 133 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
				gtk_list_store_append (_tmp3_, &_tmp4_);
#line 133 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
				iter = _tmp4_;
#line 134 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
				_tmp5_ = protoStore;
#line 134 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
				_tmp6_ = iter;
#line 134 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
				_tmp7_ = ptl;
#line 134 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
				_tmp8_ = termites_protocol_to_string (_tmp7_);
#line 134 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
				_tmp9_ = _tmp8_;
#line 134 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
				gtk_list_store_set (_tmp5_, &_tmp6_, 0, _tmp9_, -1);
#line 134 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
				_g_free0 (_tmp9_);
#line 594 "nodeProperties.c"
			}
		}
#line 131 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		ptl_collection = (g_free (ptl_collection), NULL);
#line 599 "nodeProperties.c"
	}
#line 138 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp10_ = self->priv->cbProtocol;
#line 138 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp11_ = protoStore;
#line 138 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_combo_box_set_model (_tmp10_, (GtkTreeModel*) _tmp11_);
#line 139 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp12_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 139 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_object_ref_sink (_tmp12_);
#line 139 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	cell = _tmp12_;
#line 140 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp13_ = self->priv->cbProtocol;
#line 140 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_cell_layout_pack_start ((GtkCellLayout*) _tmp13_, (GtkCellRenderer*) cell, FALSE);
#line 141 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp14_ = self->priv->cbProtocol;
#line 141 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_cell_layout_set_attributes ((GtkCellLayout*) _tmp14_, (GtkCellRenderer*) cell, "text", 0, NULL);
#line 142 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp15_ = self->priv->cbProtocol;
#line 142 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_combo_box_set_active (_tmp15_, (gint) TERMITES_PROTOCOL_SSH);
#line 128 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (cell);
#line 128 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (protoStore);
#line 629 "nodeProperties.c"
}


static gchar* bool_to_string (gboolean self) {
	gchar* result = NULL;
#line 37 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (self) {
#line 637 "nodeProperties.c"
		gchar* _tmp0_ = NULL;
#line 38 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp0_ = g_strdup ("true");
#line 38 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		result = _tmp0_;
#line 38 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		return result;
#line 645 "nodeProperties.c"
	} else {
		gchar* _tmp1_ = NULL;
#line 40 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp1_ = g_strdup ("false");
#line 40 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		result = _tmp1_;
#line 40 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		return result;
#line 654 "nodeProperties.c"
	}
}


static gboolean termites_node_properties_validate_form (TermitesNodeProperties* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GtkEntry* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
#line 145 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp2_ = self->priv->txtNodeName;
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp3_ = gtk_entry_get_text (_tmp2_);
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	if (_tmp3_ == NULL) {
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp1_ = TRUE;
#line 675 "nodeProperties.c"
	} else {
		GtkEntry* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp4_ = self->priv->txtHostname;
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp5_ = gtk_entry_get_text (_tmp4_);
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp1_ = _tmp5_ == NULL;
#line 685 "nodeProperties.c"
	}
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	if (_tmp1_) {
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp0_ = TRUE;
#line 691 "nodeProperties.c"
	} else {
		GtkEntry* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp6_ = self->priv->txtPort;
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp7_ = gtk_entry_get_text (_tmp6_);
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp0_ = _tmp7_ == NULL;
#line 701 "nodeProperties.c"
	}
#line 152 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	if (_tmp0_) {
#line 154 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		result = FALSE;
#line 154 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		return result;
#line 709 "nodeProperties.c"
	} else {
		gboolean test = FALSE;
		gboolean _tmp8_ = FALSE;
		FILE* _tmp9_ = NULL;
		gboolean _tmp10_ = FALSE;
		gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
#line 159 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp8_ = termites_node_properties_is_service_reachable (self);
#line 159 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		test = _tmp8_;
#line 160 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp9_ = stdout;
#line 160 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp10_ = test;
#line 160 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp11_ = bool_to_string (_tmp10_);
#line 160 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp12_ = _tmp11_;
#line 160 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		fprintf (_tmp9_, "recheable : %s\n", _tmp12_);
#line 160 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_g_free0 (_tmp12_);
#line 162 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		result = TRUE;
#line 162 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		return result;
#line 737 "nodeProperties.c"
	}
}


static gboolean termites_node_properties_is_service_reachable (TermitesNodeProperties* self) {
	gboolean result = FALSE;
	gboolean is_reachable = FALSE;
	GNetworkMonitor* monitor = NULL;
	GNetworkMonitor* _tmp0_ = NULL;
	GNetworkMonitor* _tmp1_ = NULL;
	GNetworkAddress* address = NULL;
	GtkEntry* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GtkEntry* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GNetworkAddress* _tmp6_ = NULL;
	GError * _inner_error_ = NULL;
#line 166 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 167 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	is_reachable = FALSE;
#line 168 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp0_ = g_network_monitor_get_default ();
#line 168 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 168 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	monitor = _tmp1_;
#line 169 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp2_ = self->priv->txtHostname;
#line 169 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp3_ = gtk_entry_get_text (_tmp2_);
#line 169 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp4_ = self->priv->txtPort;
#line 169 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp5_ = gtk_entry_get_text (_tmp4_);
#line 169 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp6_ = (GNetworkAddress*) g_network_address_new (_tmp3_, (guint16) _tmp5_);
#line 169 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	address = _tmp6_;
#line 777 "nodeProperties.c"
	{
		gboolean _tmp7_ = FALSE;
		gboolean _tmp8_ = FALSE;
#line 172 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp8_ = g_network_monitor_can_reach (monitor, (GSocketConnectable*) address, NULL, &_inner_error_);
#line 172 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_tmp7_ = _tmp8_;
#line 172 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 787 "nodeProperties.c"
			goto __catch0_g_error;
		}
#line 172 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		is_reachable = _tmp7_;
#line 792 "nodeProperties.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
#line 171 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		e = _inner_error_;
#line 171 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_inner_error_ = NULL;
#line 171 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_g_error_free0 (e);
#line 804 "nodeProperties.c"
	}
	__finally0:
#line 171 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 171 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_g_object_unref0 (address);
#line 171 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		_g_object_unref0 (monitor);
#line 171 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 171 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		g_clear_error (&_inner_error_);
#line 171 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
		return FALSE;
#line 819 "nodeProperties.c"
	}
#line 177 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	result = is_reachable;
#line 177 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (address);
#line 177 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (monitor);
#line 177 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	return result;
#line 829 "nodeProperties.c"
}


TermitesNodeProperties* termites_node_properties_construct (GType object_type) {
	TermitesNodeProperties * self = NULL;
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self = (TermitesNodeProperties*) g_object_new (object_type, NULL);
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	return self;
#line 839 "nodeProperties.c"
}


TermitesNodeProperties* termites_node_properties_new (void) {
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	return termites_node_properties_construct (TERMITES_TYPE_NODE_PROPERTIES);
#line 846 "nodeProperties.c"
}


static void termites_node_properties_class_init (TermitesNodePropertiesClass * klass) {
	gint TermitesNodeProperties_private_offset;
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	termites_node_properties_parent_class = g_type_class_peek_parent (klass);
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_type_class_add_private (klass, sizeof (TermitesNodePropertiesPrivate));
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	G_OBJECT_CLASS (klass)->finalize = termites_node_properties_finalize;
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	TermitesNodeProperties_private_offset = g_type_class_get_instance_private_offset (klass);
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/termites/ui/nodeProperties.ui");
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "txtNodeName", FALSE, TermitesNodeProperties_private_offset + G_STRUCT_OFFSET (TermitesNodePropertiesPrivate, txtNodeName));
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "txtHostname", FALSE, TermitesNodeProperties_private_offset + G_STRUCT_OFFSET (TermitesNodePropertiesPrivate, txtHostname));
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "txtPort", FALSE, TermitesNodeProperties_private_offset + G_STRUCT_OFFSET (TermitesNodePropertiesPrivate, txtPort));
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "txtUsername", FALSE, TermitesNodeProperties_private_offset + G_STRUCT_OFFSET (TermitesNodePropertiesPrivate, txtUsername));
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "cbProtocol", FALSE, TermitesNodeProperties_private_offset + G_STRUCT_OFFSET (TermitesNodePropertiesPrivate, cbProtocol));
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "cancel", G_CALLBACK(_termites_node_properties_cancel_gtk_button_clicked));
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "save_node", G_CALLBACK(_termites_node_properties_save_node_gtk_button_clicked));
#line 876 "nodeProperties.c"
}


static void termites_node_properties_instance_init (TermitesNodeProperties * self) {
	GtkEntry* _tmp0_ = NULL;
	GtkEntry* _tmp1_ = NULL;
	GtkEntry* _tmp2_ = NULL;
	GtkEntry* _tmp3_ = NULL;
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self->priv = TERMITES_NODE_PROPERTIES_GET_PRIVATE (self);
#line 37 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp0_ = (GtkEntry*) gtk_entry_new ();
#line 37 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_object_ref_sink (_tmp0_);
#line 37 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self->priv->txtNodeName = _tmp0_;
#line 40 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp1_ = (GtkEntry*) gtk_entry_new ();
#line 40 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_object_ref_sink (_tmp1_);
#line 40 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self->priv->txtHostname = _tmp1_;
#line 43 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp2_ = (GtkEntry*) gtk_entry_new ();
#line 43 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_object_ref_sink (_tmp2_);
#line 43 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self->priv->txtPort = _tmp2_;
#line 46 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_tmp3_ = (GtkEntry*) gtk_entry_new ();
#line 46 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	g_object_ref_sink (_tmp3_);
#line 46 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self->priv->txtUsername = _tmp3_;
#line 51 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self->priv->node = NULL;
#line 52 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self->priv->m_tree_view = NULL;
#line 53 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self->priv->node_emplacement = NULL;
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 919 "nodeProperties.c"
}


static void termites_node_properties_finalize (GObject* obj) {
	TermitesNodeProperties * self;
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TERMITES_TYPE_NODE_PROPERTIES, TermitesNodeProperties);
#line 37 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (self->priv->txtNodeName);
#line 40 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (self->priv->txtHostname);
#line 43 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (self->priv->txtPort);
#line 46 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (self->priv->txtUsername);
#line 49 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (self->priv->cbProtocol);
#line 51 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (self->priv->node);
#line 52 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_object_unref0 (self->priv->m_tree_view);
#line 53 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	_g_free0 (self->priv->node_emplacement);
#line 33 "/home/vincent/Source/Vala/Termites/src/nodeProperties.vala"
	G_OBJECT_CLASS (termites_node_properties_parent_class)->finalize (obj);
#line 945 "nodeProperties.c"
}


GType termites_node_properties_get_type (void) {
	static volatile gsize termites_node_properties_type_id__volatile = 0;
	if (g_once_init_enter (&termites_node_properties_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TermitesNodePropertiesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) termites_node_properties_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TermitesNodeProperties), 0, (GInstanceInitFunc) termites_node_properties_instance_init, NULL };
		GType termites_node_properties_type_id;
		termites_node_properties_type_id = g_type_register_static (gtk_dialog_get_type (), "TermitesNodeProperties", &g_define_type_info, 0);
		g_once_init_leave (&termites_node_properties_type_id__volatile, termites_node_properties_type_id);
	}
	return termites_node_properties_type_id__volatile;
}



