/* protocol.c generated by valac 0.28.1, the Vala compiler
 * generated from protocol.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * protocol.vala
 The MIT License (MIT)

 Copyright (c) 2015 Vinibo

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define TERMITES_TYPE_PROTOCOL (termites_protocol_get_type ())

typedef enum  {
	TERMITES_PROTOCOL_NONE,
	TERMITES_PROTOCOL_SSH,
	TERMITES_PROTOCOL_TELNET,
	TERMITES_PROTOCOL_SERIAL,
	TERMITES_PROTOCOL_VNC,
	TERMITES_PROTOCOL_RDP
} TermitesProtocol;



GType termites_protocol_get_type (void) G_GNUC_CONST;
TermitesProtocol* termites_protocol_all (int* result_length1);
gchar* termites_protocol_to_string (TermitesProtocol self);
TermitesProtocol termites_protocol_get (gint p_proto);


TermitesProtocol* termites_protocol_all (int* result_length1) {
	TermitesProtocol* result = NULL;
	TermitesProtocol* _tmp0_ = NULL;
	TermitesProtocol* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	_tmp0_ = g_new0 (TermitesProtocol, 6);
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	_tmp0_[0] = TERMITES_PROTOCOL_NONE;
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	_tmp0_[1] = TERMITES_PROTOCOL_SSH;
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	_tmp0_[2] = TERMITES_PROTOCOL_TELNET;
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	_tmp0_[3] = TERMITES_PROTOCOL_SERIAL;
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	_tmp0_[4] = TERMITES_PROTOCOL_VNC;
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	_tmp0_[5] = TERMITES_PROTOCOL_RDP;
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	_tmp1_ = _tmp0_;
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	_tmp1__length1 = 6;
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	if (result_length1) {
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		*result_length1 = _tmp1__length1;
#line 83 "protocol.c"
	}
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	result = _tmp1_;
#line 40 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	return result;
#line 89 "protocol.c"
}


gchar* termites_protocol_to_string (TermitesProtocol self) {
	gchar* result = NULL;
#line 44 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	switch (self) {
#line 44 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		case TERMITES_PROTOCOL_NONE:
#line 99 "protocol.c"
		{
			gchar* _tmp0_ = NULL;
#line 46 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			_tmp0_ = g_strdup ("Other");
#line 46 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			result = _tmp0_;
#line 46 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			return result;
#line 108 "protocol.c"
		}
#line 44 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		case TERMITES_PROTOCOL_SSH:
#line 112 "protocol.c"
		{
			gchar* _tmp1_ = NULL;
#line 48 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			_tmp1_ = g_strdup ("SSH");
#line 48 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			result = _tmp1_;
#line 48 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			return result;
#line 121 "protocol.c"
		}
#line 44 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		case TERMITES_PROTOCOL_TELNET:
#line 125 "protocol.c"
		{
			gchar* _tmp2_ = NULL;
#line 50 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			_tmp2_ = g_strdup ("Telnet");
#line 50 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			result = _tmp2_;
#line 50 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			return result;
#line 134 "protocol.c"
		}
#line 44 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		case TERMITES_PROTOCOL_SERIAL:
#line 138 "protocol.c"
		{
			gchar* _tmp3_ = NULL;
#line 52 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			_tmp3_ = g_strdup ("Serial");
#line 52 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			result = _tmp3_;
#line 52 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			return result;
#line 147 "protocol.c"
		}
#line 44 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		case TERMITES_PROTOCOL_VNC:
#line 151 "protocol.c"
		{
			gchar* _tmp4_ = NULL;
#line 54 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			_tmp4_ = g_strdup ("VNC");
#line 54 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			result = _tmp4_;
#line 54 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			return result;
#line 160 "protocol.c"
		}
#line 44 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		case TERMITES_PROTOCOL_RDP:
#line 164 "protocol.c"
		{
			gchar* _tmp5_ = NULL;
#line 56 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			_tmp5_ = g_strdup ("RDP");
#line 56 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			result = _tmp5_;
#line 56 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			return result;
#line 173 "protocol.c"
		}
		default:
		{
#line 58 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			g_assert_not_reached ();
#line 179 "protocol.c"
		}
	}
}


TermitesProtocol termites_protocol_get (gint p_proto) {
	TermitesProtocol result = 0;
	gint _tmp0_ = 0;
#line 63 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	_tmp0_ = p_proto;
#line 63 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
	switch (_tmp0_) {
#line 63 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		case 1:
#line 194 "protocol.c"
		{
#line 65 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			result = TERMITES_PROTOCOL_NONE;
#line 65 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			return result;
#line 200 "protocol.c"
		}
#line 63 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		case 2:
#line 204 "protocol.c"
		{
#line 67 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			result = TERMITES_PROTOCOL_SSH;
#line 67 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			return result;
#line 210 "protocol.c"
		}
#line 63 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		case 3:
#line 214 "protocol.c"
		{
#line 69 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			result = TERMITES_PROTOCOL_TELNET;
#line 69 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			return result;
#line 220 "protocol.c"
		}
#line 63 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		case 4:
#line 224 "protocol.c"
		{
#line 71 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			result = TERMITES_PROTOCOL_SERIAL;
#line 71 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			return result;
#line 230 "protocol.c"
		}
#line 63 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		case 5:
#line 234 "protocol.c"
		{
#line 73 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			result = TERMITES_PROTOCOL_VNC;
#line 73 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			return result;
#line 240 "protocol.c"
		}
#line 63 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
		case 6:
#line 244 "protocol.c"
		{
#line 75 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			result = TERMITES_PROTOCOL_RDP;
#line 75 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			return result;
#line 250 "protocol.c"
		}
		default:
		{
#line 77 "/home/vincent/Source/Vala/Termites/src/protocol.vala"
			g_assert_not_reached ();
#line 256 "protocol.c"
		}
	}
}


GType termites_protocol_get_type (void) {
	static volatile gsize termites_protocol_type_id__volatile = 0;
	if (g_once_init_enter (&termites_protocol_type_id__volatile)) {
		static const GEnumValue values[] = {{TERMITES_PROTOCOL_NONE, "TERMITES_PROTOCOL_NONE", "none"}, {TERMITES_PROTOCOL_SSH, "TERMITES_PROTOCOL_SSH", "ssh"}, {TERMITES_PROTOCOL_TELNET, "TERMITES_PROTOCOL_TELNET", "telnet"}, {TERMITES_PROTOCOL_SERIAL, "TERMITES_PROTOCOL_SERIAL", "serial"}, {TERMITES_PROTOCOL_VNC, "TERMITES_PROTOCOL_VNC", "vnc"}, {TERMITES_PROTOCOL_RDP, "TERMITES_PROTOCOL_RDP", "rdp"}, {0, NULL, NULL}};
		GType termites_protocol_type_id;
		termites_protocol_type_id = g_enum_register_static ("TermitesProtocol", values);
		g_once_init_leave (&termites_protocol_type_id__volatile, termites_protocol_type_id);
	}
	return termites_protocol_type_id__volatile;
}



