/* termiteStore.c generated by valac 0.28.1, the Vala compiler
 * generated from termiteStore.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * termiteStore.vala
 The MIT License (MIT)

 Copyright (c) 2015 Vinibo

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gio/gio.h>


#define TERMITES_TYPE_TERMITE_STORE (termites_termite_store_get_type ())
#define TERMITES_TERMITE_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStore))
#define TERMITES_TERMITE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStoreClass))
#define TERMITES_IS_TERMITE_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_TERMITE_STORE))
#define TERMITES_IS_TERMITE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_TERMITE_STORE))
#define TERMITES_TERMITE_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStoreClass))

typedef struct _TermitesTermiteStore TermitesTermiteStore;
typedef struct _TermitesTermiteStoreClass TermitesTermiteStoreClass;
typedef struct _TermitesTermiteStorePrivate TermitesTermiteStorePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TERMITES_TYPE_TERMITE_NODE (termites_termite_node_get_type ())
#define TERMITES_TERMITE_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNode))
#define TERMITES_TERMITE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNodeClass))
#define TERMITES_IS_TERMITE_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_TERMITE_NODE))
#define TERMITES_IS_TERMITE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_TERMITE_NODE))
#define TERMITES_TERMITE_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNodeClass))

typedef struct _TermitesTermiteNode TermitesTermiteNode;
typedef struct _TermitesTermiteNodeClass TermitesTermiteNodeClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block1Data Block1Data;

struct _TermitesTermiteStore {
	GObject parent_instance;
	TermitesTermiteStorePrivate * priv;
};

struct _TermitesTermiteStoreClass {
	GObjectClass parent_class;
};

struct _TermitesTermiteStorePrivate {
	GtkTreeStore* termiteNodes;
};

struct _Block1Data {
	int _ref_count_;
	GDataOutputStream* file;
};


static gpointer termites_termite_store_parent_class = NULL;

GType termites_termite_store_get_type (void) G_GNUC_CONST;
#define TERMITES_TERMITE_STORE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStorePrivate))
enum  {
	TERMITES_TERMITE_STORE_DUMMY_PROPERTY
};
TermitesTermiteStore* termites_termite_store_new (void);
TermitesTermiteStore* termites_termite_store_construct (GType object_type);
GType termites_termite_node_get_type (void) G_GNUC_CONST;
void termites_termite_store_add_node (TermitesTermiteStore* self, TermitesTermiteNode* node, GtkTreeIter* position, GtkTreeIter* position_inserted);
const gchar* termites_termite_node_get_name (TermitesTermiteNode* self);
void termites_termite_store_update_node (TermitesTermiteStore* self, TermitesTermiteNode* node, GtkTreeIter* position);
void termites_termite_store_delete_node (TermitesTermiteStore* self, GtkTreeIter* position);
void termites_termite_store_clear_tree (TermitesTermiteStore* self);
GtkTreeStore* termites_termite_store_get_tree (TermitesTermiteStore* self);
GtkTreeIter* termites_termite_store_convert_string_to_new_iter (TermitesTermiteStore* self, const gchar* path_to_convert);
static GtkTreeIter* _gtk_tree_iter_dup (GtkTreeIter* self);
GtkTreeModelForeachFunc termites_termite_store_generate_save_delegate (GDataOutputStream* file, void** result_target, GDestroyNotify* result_target_destroy_notify);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static gboolean __lambda4_ (Block1Data* _data1_, GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter);
gchar* termites_termite_node_serialize (TermitesTermiteNode* self);
static gboolean ___lambda4__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self);
static void termites_termite_store_finalize (GObject* obj);


TermitesTermiteStore* termites_termite_store_construct (GType object_type) {
	TermitesTermiteStore * self = NULL;
	GtkTreeStore* _tmp0_ = NULL;
#line 35 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	self = (TermitesTermiteStore*) g_object_new (object_type, NULL);
#line 36 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp0_ = gtk_tree_store_new (2, G_TYPE_STRING, TERMITES_TYPE_TERMITE_NODE);
#line 36 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_g_object_unref0 (self->priv->termiteNodes);
#line 36 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	self->priv->termiteNodes = _tmp0_;
#line 35 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	return self;
#line 123 "termiteStore.c"
}


TermitesTermiteStore* termites_termite_store_new (void) {
#line 35 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	return termites_termite_store_construct (TERMITES_TYPE_TERMITE_STORE);
#line 130 "termiteStore.c"
}


void termites_termite_store_add_node (TermitesTermiteStore* self, TermitesTermiteNode* node, GtkTreeIter* position, GtkTreeIter* position_inserted) {
	GtkTreeIter _vala_position_inserted = {0};
	GtkTreeIter new_position_in_tree = {0};
	GtkTreeStore* _tmp0_ = NULL;
	GtkTreeIter* _tmp1_ = NULL;
	GtkTreeIter _tmp2_ = {0};
	GtkTreeStore* _tmp3_ = NULL;
	GtkTreeIter _tmp4_ = {0};
	TermitesTermiteNode* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	TermitesTermiteNode* _tmp8_ = NULL;
	GtkTreeIter _tmp9_ = {0};
#line 39 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_if_fail (self != NULL);
#line 39 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_if_fail (node != NULL);
#line 42 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp0_ = self->priv->termiteNodes;
#line 42 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp1_ = position;
#line 42 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	gtk_tree_store_append (_tmp0_, &_tmp2_, _tmp1_);
#line 42 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	new_position_in_tree = _tmp2_;
#line 43 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp3_ = self->priv->termiteNodes;
#line 43 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp4_ = new_position_in_tree;
#line 43 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp5_ = node;
#line 43 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp6_ = termites_termite_node_get_name (_tmp5_);
#line 43 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp7_ = _tmp6_;
#line 43 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp8_ = node;
#line 43 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	gtk_tree_store_set (_tmp3_, &_tmp4_, 0, _tmp7_, 1, _tmp8_, -1, -1);
#line 44 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp9_ = new_position_in_tree;
#line 44 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_vala_position_inserted = _tmp9_;
#line 39 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	if (position_inserted) {
#line 39 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
		*position_inserted = _vala_position_inserted;
#line 181 "termiteStore.c"
	}
}


void termites_termite_store_update_node (TermitesTermiteStore* self, TermitesTermiteNode* node, GtkTreeIter* position) {
	GtkTreeStore* _tmp0_ = NULL;
	GtkTreeIter _tmp1_ = {0};
	TermitesTermiteNode* _tmp2_ = NULL;
	GValue _tmp3_ = {0};
	GtkTreeStore* _tmp4_ = NULL;
	GtkTreeIter _tmp5_ = {0};
	TermitesTermiteNode* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	GValue _tmp9_ = {0};
#line 47 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_if_fail (self != NULL);
#line 47 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_if_fail (node != NULL);
#line 47 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_if_fail (position != NULL);
#line 48 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp0_ = self->priv->termiteNodes;
#line 48 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp1_ = *position;
#line 48 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp2_ = node;
#line 48 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_value_init (&_tmp3_, TERMITES_TYPE_TERMITE_NODE);
#line 48 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_value_set_object (&_tmp3_, _tmp2_);
#line 48 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	gtk_tree_store_set_value (_tmp0_, &_tmp1_, 1, &_tmp3_);
#line 48 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	G_IS_VALUE (&_tmp3_) ? (g_value_unset (&_tmp3_), NULL) : NULL;
#line 49 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp4_ = self->priv->termiteNodes;
#line 49 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp5_ = *position;
#line 49 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp6_ = node;
#line 49 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp7_ = termites_termite_node_get_name (_tmp6_);
#line 49 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp8_ = _tmp7_;
#line 49 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_value_init (&_tmp9_, G_TYPE_STRING);
#line 49 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_value_set_string (&_tmp9_, _tmp8_);
#line 49 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	gtk_tree_store_set_value (_tmp4_, &_tmp5_, 0, &_tmp9_);
#line 49 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	G_IS_VALUE (&_tmp9_) ? (g_value_unset (&_tmp9_), NULL) : NULL;
#line 235 "termiteStore.c"
}


static gchar* bool_to_string (gboolean self) {
	gchar* result = NULL;
#line 37 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (self) {
#line 243 "termiteStore.c"
		gchar* _tmp0_ = NULL;
#line 38 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp0_ = g_strdup ("true");
#line 38 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		result = _tmp0_;
#line 38 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		return result;
#line 251 "termiteStore.c"
	} else {
		gchar* _tmp1_ = NULL;
#line 40 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp1_ = g_strdup ("false");
#line 40 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		result = _tmp1_;
#line 40 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		return result;
#line 260 "termiteStore.c"
	}
}


void termites_termite_store_delete_node (TermitesTermiteStore* self, GtkTreeIter* position) {
	gboolean has_child = FALSE;
	GtkTreeStore* _tmp0_ = NULL;
	GtkTreeIter _tmp1_ = {0};
	gboolean _tmp2_ = FALSE;
	FILE* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	GtkTreeStore* _tmp6_ = NULL;
#line 52 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_if_fail (self != NULL);
#line 52 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_if_fail (position != NULL);
#line 53 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp0_ = self->priv->termiteNodes;
#line 53 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp1_ = *position;
#line 53 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp2_ = gtk_tree_model_iter_has_child ((GtkTreeModel*) _tmp0_, &_tmp1_);
#line 53 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	has_child = _tmp2_;
#line 54 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp3_ = stdout;
#line 54 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp4_ = bool_to_string (has_child);
#line 54 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp5_ = _tmp4_;
#line 54 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	fprintf (_tmp3_, "Has children? : %s\n", _tmp5_);
#line 54 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_g_free0 (_tmp5_);
#line 55 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp6_ = self->priv->termiteNodes;
#line 55 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	gtk_tree_store_remove (_tmp6_, position);
#line 300 "termiteStore.c"
}


void termites_termite_store_clear_tree (TermitesTermiteStore* self) {
	GtkTreeStore* _tmp0_ = NULL;
#line 61 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_if_fail (self != NULL);
#line 62 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp0_ = self->priv->termiteNodes;
#line 62 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	gtk_tree_store_clear (_tmp0_);
#line 312 "termiteStore.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 66 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	return self ? g_object_ref (self) : NULL;
#line 319 "termiteStore.c"
}


GtkTreeStore* termites_termite_store_get_tree (TermitesTermiteStore* self) {
	GtkTreeStore* result = NULL;
	GtkTreeStore* _tmp0_ = NULL;
	GtkTreeStore* _tmp1_ = NULL;
#line 65 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 66 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp0_ = self->priv->termiteNodes;
#line 66 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 66 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	result = _tmp1_;
#line 66 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	return result;
#line 337 "termiteStore.c"
}


static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 900 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 900 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, 0);
#line 901 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp0_ = start_index;
#line 901 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp1_ = needle;
#line 901 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
#line 901 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_result_ = _tmp2_;
#line 903 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp3_ = _result_;
#line 903 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (_tmp3_ != NULL) {
#line 364 "termiteStore.c"
		gchar* _tmp4_ = NULL;
#line 904 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp4_ = _result_;
#line 904 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		result = (gint) (_tmp4_ - ((gchar*) self));
#line 904 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		return result;
#line 372 "termiteStore.c"
	} else {
#line 906 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		result = -1;
#line 906 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		return result;
#line 378 "termiteStore.c"
	}
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	glong string_length = 0L;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	glong _tmp2_ = 0L;
	glong _tmp5_ = 0L;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_ = 0L;
	gboolean _tmp12_ = FALSE;
	glong _tmp13_ = 0L;
	glong _tmp16_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	gchar* _tmp21_ = NULL;
#line 1230 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1231 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp0_ = strlen (self);
#line 1231 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp1_ = _tmp0_;
#line 1231 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	string_length = (glong) _tmp1_;
#line 1232 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp2_ = start;
#line 1232 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (_tmp2_ < ((glong) 0)) {
#line 412 "termiteStore.c"
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
#line 1233 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp3_ = string_length;
#line 1233 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp4_ = start;
#line 1233 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		start = _tmp3_ + _tmp4_;
#line 421 "termiteStore.c"
	}
#line 1235 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp5_ = end;
#line 1235 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (_tmp5_ < ((glong) 0)) {
#line 427 "termiteStore.c"
		glong _tmp6_ = 0L;
		glong _tmp7_ = 0L;
#line 1236 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp6_ = string_length;
#line 1236 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp7_ = end;
#line 1236 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		end = _tmp6_ + _tmp7_;
#line 436 "termiteStore.c"
	}
#line 1238 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp9_ = start;
#line 1238 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (_tmp9_ >= ((glong) 0)) {
#line 442 "termiteStore.c"
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
#line 1238 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp10_ = start;
#line 1238 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp11_ = string_length;
#line 1238 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp8_ = _tmp10_ <= _tmp11_;
#line 451 "termiteStore.c"
	} else {
#line 1238 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp8_ = FALSE;
#line 455 "termiteStore.c"
	}
#line 1238 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail (_tmp8_, NULL);
#line 1239 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp13_ = end;
#line 1239 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (_tmp13_ >= ((glong) 0)) {
#line 463 "termiteStore.c"
		glong _tmp14_ = 0L;
		glong _tmp15_ = 0L;
#line 1239 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp14_ = end;
#line 1239 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp15_ = string_length;
#line 1239 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp12_ = _tmp14_ <= _tmp15_;
#line 472 "termiteStore.c"
	} else {
#line 1239 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp12_ = FALSE;
#line 476 "termiteStore.c"
	}
#line 1239 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail (_tmp12_, NULL);
#line 1240 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp16_ = start;
#line 1240 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp17_ = end;
#line 1240 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail (_tmp16_ <= _tmp17_, NULL);
#line 1241 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp18_ = start;
#line 1241 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp19_ = end;
#line 1241 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp20_ = start;
#line 1241 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp21_ = g_strndup (((gchar*) self) + _tmp18_, (gsize) (_tmp19_ - _tmp20_));
#line 1241 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	result = _tmp21_;
#line 1241 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	return result;
#line 498 "termiteStore.c"
}


static GtkTreeIter* _gtk_tree_iter_dup (GtkTreeIter* self) {
	GtkTreeIter* dup;
#line 78 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	dup = g_new0 (GtkTreeIter, 1);
#line 78 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	memcpy (dup, self, sizeof (GtkTreeIter));
#line 78 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	return dup;
#line 510 "termiteStore.c"
}


static gpointer __gtk_tree_iter_dup0 (gpointer self) {
#line 78 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	return self ? _gtk_tree_iter_dup (self) : NULL;
#line 517 "termiteStore.c"
}


GtkTreeIter* termites_termite_store_convert_string_to_new_iter (TermitesTermiteStore* self, const gchar* path_to_convert) {
	GtkTreeIter* result = NULL;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gchar* latest_position = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	gchar* _tmp6_ = NULL;
	GtkTreeIter iter_in_tree = {0};
	GtkTreeStore* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	GtkTreeIter _tmp9_ = {0};
	GtkTreeIter* _tmp10_ = NULL;
#line 69 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 69 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_val_if_fail (path_to_convert != NULL, NULL);
#line 70 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp0_ = path_to_convert;
#line 70 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp1_ = string_index_of (_tmp0_, ":", 0);
#line 70 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	if (_tmp1_ < 1) {
#line 71 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
		result = NULL;
#line 71 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
		return result;
#line 550 "termiteStore.c"
	}
#line 74 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp2_ = path_to_convert;
#line 74 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp3_ = path_to_convert;
#line 74 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp4_ = strlen (_tmp3_);
#line 74 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp5_ = _tmp4_;
#line 74 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp6_ = string_slice (_tmp2_, (glong) 0, (glong) (_tmp5_ - 2));
#line 74 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	latest_position = _tmp6_;
#line 76 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp7_ = self->priv->termiteNodes;
#line 76 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp8_ = latest_position;
#line 76 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	gtk_tree_model_get_iter_from_string ((GtkTreeModel*) _tmp7_, &_tmp9_, _tmp8_);
#line 76 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	iter_in_tree = _tmp9_;
#line 78 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp10_ = __gtk_tree_iter_dup0 (&iter_in_tree);
#line 78 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	result = _tmp10_;
#line 78 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_g_free0 (latest_position);
#line 78 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	return result;
#line 580 "termiteStore.c"
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
#line 81 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 81 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	return _data1_;
#line 589 "termiteStore.c"
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 81 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 81 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
		_g_object_unref0 (_data1_->file);
#line 81 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
		g_slice_free (Block1Data, _data1_);
#line 602 "termiteStore.c"
	}
}


static gboolean __lambda4_ (Block1Data* _data1_, GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter) {
	gboolean result = FALSE;
	GValue node_from_tree = {0};
	GtkTreeModel* _tmp0_ = NULL;
	GtkTreeIter _tmp1_ = {0};
	GValue _tmp2_ = {0};
	TermitesTermiteNode* node = NULL;
	GValue _tmp3_ = {0};
	TermitesTermiteNode* _tmp4_ = NULL;
	gchar* iter_string = NULL;
	GtkTreeModel* _tmp5_ = NULL;
	GtkTreeIter _tmp6_ = {0};
	gchar* _tmp7_ = NULL;
	FILE* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	GDataOutputStream* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	GError * _inner_error_ = NULL;
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_val_if_fail (model != NULL, FALSE);
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_val_if_fail (path != NULL, FALSE);
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_val_if_fail (iter != NULL, FALSE);
#line 84 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp0_ = model;
#line 84 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp1_ = *iter;
#line 84 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	gtk_tree_model_get_value (_tmp0_, &_tmp1_, 1, &_tmp2_);
#line 84 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	G_IS_VALUE (&node_from_tree) ? (g_value_unset (&node_from_tree), NULL) : NULL;
#line 84 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	node_from_tree = _tmp2_;
#line 86 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp3_ = node_from_tree;
#line 86 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp4_ = _g_object_ref0 (g_value_get_object (&_tmp3_));
#line 86 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	node = _tmp4_;
#line 87 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp5_ = model;
#line 87 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp6_ = *iter;
#line 87 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp7_ = gtk_tree_model_get_string_from_iter (_tmp5_, &_tmp6_);
#line 87 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	iter_string = _tmp7_;
#line 88 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp8_ = stdout;
#line 88 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp9_ = termites_termite_node_serialize (node);
#line 88 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp10_ = _tmp9_;
#line 88 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	fprintf (_tmp8_, "Position of node %s in tree : %s\n", iter_string, _tmp10_);
#line 88 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_g_free0 (_tmp10_);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp11_ = _data1_->file;
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp12_ = g_strconcat (iter_string, ",", NULL);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp13_ = _tmp12_;
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp14_ = termites_termite_node_serialize (node);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp15_ = _tmp14_;
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp16_ = g_strconcat (_tmp13_, _tmp15_, NULL);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp17_ = _tmp16_;
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp18_ = g_strconcat (_tmp17_, "\n", NULL);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp19_ = _tmp18_;
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_data_output_stream_put_string (_tmp11_, _tmp19_, NULL, &_inner_error_);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_g_free0 (_tmp19_);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_g_free0 (_tmp17_);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_g_free0 (_tmp15_);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_g_free0 (_tmp13_);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
		_g_free0 (iter_string);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
		_g_object_unref0 (node);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
		G_IS_VALUE (&node_from_tree) ? (g_value_unset (&node_from_tree), NULL) : NULL;
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
		g_clear_error (&_inner_error_);
#line 90 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
		return FALSE;
#line 715 "termiteStore.c"
	}
#line 92 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	result = FALSE;
#line 92 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_g_free0 (iter_string);
#line 92 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_g_object_unref0 (node);
#line 92 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	G_IS_VALUE (&node_from_tree) ? (g_value_unset (&node_from_tree), NULL) : NULL;
#line 92 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	return result;
#line 727 "termiteStore.c"
}


static gboolean ___lambda4__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self) {
	gboolean result;
	result = __lambda4_ (self, model, path, iter);
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	return result;
#line 736 "termiteStore.c"
}


GtkTreeModelForeachFunc termites_termite_store_generate_save_delegate (GDataOutputStream* file, void** result_target, GDestroyNotify* result_target_destroy_notify) {
	GtkTreeModelForeachFunc result = NULL;
	Block1Data* _data1_;
	GDataOutputStream* _tmp0_ = NULL;
	GDataOutputStream* _tmp1_ = NULL;
	GtkTreeModelForeachFunc _tmp2_ = NULL;
	void* _tmp2__target = NULL;
	GDestroyNotify _tmp2__target_destroy_notify = NULL;
#line 81 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_return_val_if_fail (file != NULL, NULL);
#line 81 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 81 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_data1_->_ref_count_ = 1;
#line 81 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp0_ = file;
#line 81 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 81 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_g_object_unref0 (_data1_->file);
#line 81 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_data1_->file = _tmp1_;
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp2_ = ___lambda4__gtk_tree_model_foreach_func;
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp2__target = block1_data_ref (_data1_);
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_tmp2__target_destroy_notify = block1_data_unref;
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	*result_target = _tmp2__target;
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	*result_target_destroy_notify = _tmp2__target_destroy_notify;
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	result = _tmp2_;
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	block1_data_unref (_data1_);
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_data1_ = NULL;
#line 82 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	return result;
#line 780 "termiteStore.c"
}


static void termites_termite_store_class_init (TermitesTermiteStoreClass * klass) {
#line 31 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	termites_termite_store_parent_class = g_type_class_peek_parent (klass);
#line 31 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	g_type_class_add_private (klass, sizeof (TermitesTermiteStorePrivate));
#line 31 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	G_OBJECT_CLASS (klass)->finalize = termites_termite_store_finalize;
#line 791 "termiteStore.c"
}


static void termites_termite_store_instance_init (TermitesTermiteStore * self) {
#line 31 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	self->priv = TERMITES_TERMITE_STORE_GET_PRIVATE (self);
#line 798 "termiteStore.c"
}


static void termites_termite_store_finalize (GObject* obj) {
	TermitesTermiteStore * self;
#line 31 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStore);
#line 33 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	_g_object_unref0 (self->priv->termiteNodes);
#line 31 "/home/vincent/Source/Vala/Termites/src/termiteStore.vala"
	G_OBJECT_CLASS (termites_termite_store_parent_class)->finalize (obj);
#line 810 "termiteStore.c"
}


GType termites_termite_store_get_type (void) {
	static volatile gsize termites_termite_store_type_id__volatile = 0;
	if (g_once_init_enter (&termites_termite_store_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TermitesTermiteStoreClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) termites_termite_store_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TermitesTermiteStore), 0, (GInstanceInitFunc) termites_termite_store_instance_init, NULL };
		GType termites_termite_store_type_id;
		termites_termite_store_type_id = g_type_register_static (G_TYPE_OBJECT, "TermitesTermiteStore", &g_define_type_info, 0);
		g_once_init_leave (&termites_termite_store_type_id__volatile, termites_termite_store_type_id);
	}
	return termites_termite_store_type_id__volatile;
}



