/* termites.c generated by valac 0.28.1, the Vala compiler
 * generated from termites.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * termites.vala
 The MIT License (MIT)

 Copyright (c) 2015 Vinibo

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <stdio.h>
#include <vte/vte.h>


#define TERMITES_TYPE_TERMITES (termites_termites_get_type ())
#define TERMITES_TERMITES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_TERMITES, TermitesTermites))
#define TERMITES_TERMITES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_TERMITES, TermitesTermitesClass))
#define TERMITES_IS_TERMITES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_TERMITES))
#define TERMITES_IS_TERMITES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_TERMITES))
#define TERMITES_TERMITES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_TERMITES, TermitesTermitesClass))

typedef struct _TermitesTermites TermitesTermites;
typedef struct _TermitesTermitesClass TermitesTermitesClass;
typedef struct _TermitesTermitesPrivate TermitesTermitesPrivate;

#define TERMITES_TYPE_TERMITE_STORE (termites_termite_store_get_type ())
#define TERMITES_TERMITE_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStore))
#define TERMITES_TERMITE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStoreClass))
#define TERMITES_IS_TERMITE_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_TERMITE_STORE))
#define TERMITES_IS_TERMITE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_TERMITE_STORE))
#define TERMITES_TERMITE_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_TERMITE_STORE, TermitesTermiteStoreClass))

typedef struct _TermitesTermiteStore TermitesTermiteStore;
typedef struct _TermitesTermiteStoreClass TermitesTermiteStoreClass;

#define TERMITES_TYPE_CONFIG (termites_config_get_type ())
#define TERMITES_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_CONFIG, TermitesConfig))
#define TERMITES_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_CONFIG, TermitesConfigClass))
#define TERMITES_IS_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_CONFIG))
#define TERMITES_IS_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_CONFIG))
#define TERMITES_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_CONFIG, TermitesConfigClass))

typedef struct _TermitesConfig TermitesConfig;
typedef struct _TermitesConfigClass TermitesConfigClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define TERMITES_TYPE_NODE_PROPERTIES (termites_node_properties_get_type ())
#define TERMITES_NODE_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_NODE_PROPERTIES, TermitesNodeProperties))
#define TERMITES_NODE_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_NODE_PROPERTIES, TermitesNodePropertiesClass))
#define TERMITES_IS_NODE_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_NODE_PROPERTIES))
#define TERMITES_IS_NODE_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_NODE_PROPERTIES))
#define TERMITES_NODE_PROPERTIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_NODE_PROPERTIES, TermitesNodePropertiesClass))

typedef struct _TermitesNodeProperties TermitesNodeProperties;
typedef struct _TermitesNodePropertiesClass TermitesNodePropertiesClass;
typedef struct _Block2Data Block2Data;
typedef struct _Block3Data Block3Data;

#define TERMITES_TYPE_TERMITE_NODE (termites_termite_node_get_type ())
#define TERMITES_TERMITE_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNode))
#define TERMITES_TERMITE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNodeClass))
#define TERMITES_IS_TERMITE_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TERMITES_TYPE_TERMITE_NODE))
#define TERMITES_IS_TERMITE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMITES_TYPE_TERMITE_NODE))
#define TERMITES_TERMITE_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMITES_TYPE_TERMITE_NODE, TermitesTermiteNodeClass))

typedef struct _TermitesTermiteNode TermitesTermiteNode;
typedef struct _TermitesTermiteNodeClass TermitesTermiteNodeClass;
typedef struct _Block4Data Block4Data;

struct _TermitesTermites {
	GtkApplicationWindow parent_instance;
	TermitesTermitesPrivate * priv;
};

struct _TermitesTermitesClass {
	GtkApplicationWindowClass parent_class;
};

struct _TermitesTermitesPrivate {
	GtkTreeView* terminalTreeview;
	GtkNotebook* terminalTabs;
	GtkLabel* lblSession;
	TermitesTermiteStore* termite_tree_store;
	TermitesConfig* m_configuration;
};

struct _Block2Data {
	int _ref_count_;
	TermitesTermites* self;
	GtkTreeIter node_emplacement;
	GtkMessageDialog* msg;
};

struct _Block3Data {
	int _ref_count_;
	TermitesTermites* self;
	VteTerminal* testTerm;
};

struct _Block4Data {
	int _ref_count_;
	TermitesTermites* self;
	GtkWidget* p_term_tab;
};


static gpointer termites_termites_parent_class = NULL;

#define TERMITES_UI_ABOUT "ui/aboutTermites.ui"
#define TERMITES_SSH_BINARY_PATH "/usr/bin/ssh"
GType termites_termites_get_type (void) G_GNUC_CONST;
GType termites_termite_store_get_type (void) G_GNUC_CONST;
GType termites_config_get_type (void) G_GNUC_CONST;
#define TERMITES_TERMITES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TERMITES_TYPE_TERMITES, TermitesTermitesPrivate))
enum  {
	TERMITES_TERMITES_DUMMY_PROPERTY
};
static gint termites_termites_main (gchar** args, int args_length1);
TermitesTermites* termites_termites_new (void);
TermitesTermites* termites_termites_construct (GType object_type);
TermitesConfig* termites_config_new (void);
TermitesConfig* termites_config_construct (GType object_type);
TermitesTermiteStore* termites_termite_store_new (void);
TermitesTermiteStore* termites_termite_store_construct (GType object_type);
GtkTreeStore* termites_termite_store_get_tree (TermitesTermiteStore* self);
void termites_termites_on_destroy (TermitesTermites* self, GtkWidget* window);
static void _termites_termites_on_destroy_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
void termites_termites_quit_termites (TermitesTermites* self, GtkWidget* window);
static void _termites_termites_quit_termites_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
void termites_termites_open_tree (TermitesTermites* self);
void termites_file_helper_load_termites_tree (const gchar* file_path, TermitesTermiteStore* termites);
static void _termites_termites_open_tree_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
void termites_termites_save_tree (TermitesTermites* self);
void termites_file_helper_save_termites_tree (const gchar* file_path, GtkTreeStore* termites);
static void _termites_termites_save_tree_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
void termites_termites_save_tree_as (TermitesTermites* self);
static void _termites_termites_save_tree_as_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
void termites_termites_about_termites (TermitesTermites* self);
gchar* termites_application_get_version_string (void);
static void _termites_termites_about_termites_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
void termites_termites_create_node (TermitesTermites* self);
GType termites_node_properties_get_type (void) G_GNUC_CONST;
TermitesNodeProperties* termites_node_properties_new_new (TermitesTermiteStore** termites);
TermitesNodeProperties* termites_node_properties_construct_new (GType object_type, TermitesTermiteStore** termites);
void termites_node_properties_show_window (TermitesNodeProperties* self, GtkWindow* p_parent_window);
static void _termites_termites_create_node_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
void termites_termites_modify_node (TermitesTermites* self);
TermitesNodeProperties* termites_node_properties_new_edit (TermitesTermiteStore** termites, GtkTreeSelection* selected_node);
TermitesNodeProperties* termites_node_properties_construct_edit (GType object_type, TermitesTermiteStore** termites, GtkTreeSelection* selected_node);
static void _termites_termites_modify_node_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
void termites_termites_remove_node (TermitesTermites* self);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void __lambda5_ (Block2Data* _data2_, gint response_id);
void termites_termite_store_delete_node (TermitesTermiteStore* self, GtkTreeIter* position);
static void ___lambda5__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
static void _termites_termites_remove_node_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
void termites_termites_open_connection (TermitesTermites* self, GtkTreeView* p_view, GtkTreePath* p_root, GtkTreeViewColumn* p_column);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
GType termites_termite_node_get_type (void) G_GNUC_CONST;
static TermitesTermiteNode* termites_termites_get_selection (GtkTreeModel* p_model, GtkTreeIter* p_iter);
const gchar* termites_termite_node_get_host (TermitesTermiteNode* self);
gchar* termites_termite_node_serialize (TermitesTermiteNode* self);
gchar* termites_termite_node_get_connection_string (TermitesTermiteNode* self);
static void ___lambda6_ (Block3Data* _data3_, gint t);
static void ____lambda6__vte_terminal_child_exited (VteTerminal* _sender, gint status, gpointer self);
static GtkWidget* termites_termites_create_notebook_child_label (TermitesTermites* self, const gchar* p_text, GtkWidget* p_term_tab);
const gchar* termites_termite_node_get_name (TermitesTermiteNode* self);
void termites_termites_reorganise_tabs (TermitesTermites* self);
static void _termites_termites_open_connection_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self);
static void _termites_termites_reorganise_tabs_gtk_notebook_page_removed (GtkNotebook* _sender, GtkWidget* child, guint page_num, gpointer self);
void termites_termites_open_settings (TermitesTermites* self);
static void _termites_termites_open_settings_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static Block4Data* block4_data_ref (Block4Data* _data4_);
static void block4_data_unref (void * _userdata_);
static void __lambda7_ (Block4Data* _data4_, GtkButton* t);
static void ___lambda7__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void termites_termites_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gint termites_termites_main (gchar** args, int args_length1) {
	gint result = 0;
	TermitesTermites* win = NULL;
	TermitesTermites* _tmp0_ = NULL;
#line 53 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_init (&args_length1, &args);
#line 54 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = termites_termites_new ();
#line 54 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp0_);
#line 54 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	win = _tmp0_;
#line 55 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_window_present ((GtkWindow*) win);
#line 56 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_main ();
#line 57 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	result = 0;
#line 57 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (win);
#line 57 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	return result;
#line 233 "termites.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 52 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	return termites_termites_main (argv, argc);
#line 243 "termites.c"
}


TermitesTermites* termites_termites_construct (GType object_type) {
	TermitesTermites * self = NULL;
	TermitesConfig* _tmp0_ = NULL;
	TermitesTermiteStore* _tmp1_ = NULL;
	GtkTreeView* _tmp2_ = NULL;
	TermitesTermiteStore* _tmp3_ = NULL;
	GtkTreeStore* _tmp4_ = NULL;
	GtkTreeStore* _tmp5_ = NULL;
	GtkCellRendererText* cell = NULL;
	GtkCellRendererText* _tmp6_ = NULL;
	GtkTreeView* _tmp7_ = NULL;
#line 60 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	self = (TermitesTermites*) g_object_new (object_type, NULL);
#line 63 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = termites_config_new ();
#line 63 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp0_);
#line 63 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (self->priv->m_configuration);
#line 63 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	self->priv->m_configuration = _tmp0_;
#line 65 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = termites_termite_store_new ();
#line 65 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (self->priv->termite_tree_store);
#line 65 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	self->priv->termite_tree_store = _tmp1_;
#line 66 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp2_ = self->priv->terminalTreeview;
#line 66 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp3_ = self->priv->termite_tree_store;
#line 66 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp4_ = termites_termite_store_get_tree (_tmp3_);
#line 66 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp5_ = _tmp4_;
#line 66 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_tree_view_set_model (_tmp2_, (GtkTreeModel*) _tmp5_);
#line 66 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (_tmp5_);
#line 68 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp6_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 68 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp6_);
#line 68 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	cell = _tmp6_;
#line 69 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp7_ = self->priv->terminalTreeview;
#line 69 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_tree_view_insert_column_with_attributes (_tmp7_, -1, "Name", (GtkCellRenderer*) cell, "text", 0, NULL, NULL);
#line 60 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (cell);
#line 60 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	return self;
#line 300 "termites.c"
}


TermitesTermites* termites_termites_new (void) {
#line 60 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	return termites_termites_construct (TERMITES_TYPE_TERMITES);
#line 307 "termites.c"
}


void termites_termites_on_destroy (TermitesTermites* self, GtkWidget* window) {
#line 73 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (self != NULL);
#line 73 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (window != NULL);
#line 75 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_main_quit ();
#line 318 "termites.c"
}


static void _termites_termites_on_destroy_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_on_destroy ((TermitesTermites*) self, _sender);
#line 325 "termites.c"
}


void termites_termites_quit_termites (TermitesTermites* self, GtkWidget* window) {
#line 79 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (self != NULL);
#line 79 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (window != NULL);
#line 81 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_main_quit ();
#line 336 "termites.c"
}


static void _termites_termites_quit_termites_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_quit_termites ((TermitesTermites*) self, _sender);
#line 343 "termites.c"
}


void termites_termites_open_tree (TermitesTermites* self) {
	GtkFileChooserDialog* chooser = NULL;
	GtkFileChooserDialog* _tmp0_ = NULL;
	GtkFileChooserDialog* _tmp1_ = NULL;
	GtkFileChooserDialog* _tmp2_ = NULL;
	gint _tmp3_ = 0;
#line 85 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (self != NULL);
#line 86 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = (GtkFileChooserDialog*) gtk_file_chooser_dialog_new ("Save nodes", (GtkWindow*) self, GTK_FILE_CHOOSER_ACTION_OPEN, "Cancel", GTK_RESPONSE_CANCEL, "Open", GTK_RESPONSE_ACCEPT, NULL, NULL);
#line 86 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp0_);
#line 86 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	chooser = _tmp0_;
#line 93 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = chooser;
#line 93 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_show ((GtkWidget*) _tmp1_);
#line 94 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp2_ = chooser;
#line 94 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp3_ = gtk_dialog_run ((GtkDialog*) _tmp2_);
#line 94 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	if (_tmp3_ == ((gint) GTK_RESPONSE_ACCEPT)) {
#line 371 "termites.c"
		gchar* uri = NULL;
		GtkFileChooserDialog* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		TermitesTermiteStore* _tmp7_ = NULL;
		GtkFileChooserDialog* _tmp8_ = NULL;
#line 95 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp4_ = chooser;
#line 95 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp5_ = gtk_file_chooser_get_uri ((GtkFileChooser*) _tmp4_);
#line 95 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		uri = _tmp5_;
#line 96 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp6_ = uri;
#line 96 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp7_ = self->priv->termite_tree_store;
#line 96 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		termites_file_helper_load_termites_tree (_tmp6_, _tmp7_);
#line 97 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp8_ = chooser;
#line 97 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_signal_emit_by_name ((GtkDialog*) _tmp8_, "close");
#line 94 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_free0 (uri);
#line 396 "termites.c"
	} else {
		GtkFileChooserDialog* _tmp9_ = NULL;
#line 99 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp9_ = chooser;
#line 99 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_signal_emit_by_name ((GtkDialog*) _tmp9_, "close");
#line 403 "termites.c"
	}
#line 85 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (chooser);
#line 407 "termites.c"
}


static void _termites_termites_open_tree_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_open_tree ((TermitesTermites*) self);
#line 414 "termites.c"
}


void termites_termites_save_tree (TermitesTermites* self) {
	TermitesTermiteStore* _tmp0_ = NULL;
	GtkTreeStore* _tmp1_ = NULL;
	GtkTreeStore* _tmp2_ = NULL;
#line 104 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (self != NULL);
#line 108 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = self->priv->termite_tree_store;
#line 108 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = termites_termite_store_get_tree (_tmp0_);
#line 108 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp2_ = _tmp1_;
#line 108 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_file_helper_save_termites_tree ("termitesTests.ter", _tmp2_);
#line 108 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (_tmp2_);
#line 434 "termites.c"
}


static void _termites_termites_save_tree_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_save_tree ((TermitesTermites*) self);
#line 441 "termites.c"
}


void termites_termites_save_tree_as (TermitesTermites* self) {
	GtkFileChooserDialog* chooser = NULL;
	GtkFileChooserDialog* _tmp0_ = NULL;
	GtkFileChooserDialog* _tmp1_ = NULL;
	GtkFileChooserDialog* _tmp2_ = NULL;
	gint _tmp3_ = 0;
#line 112 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (self != NULL);
#line 113 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = (GtkFileChooserDialog*) gtk_file_chooser_dialog_new ("Save nodes", (GtkWindow*) self, GTK_FILE_CHOOSER_ACTION_SAVE, "Cancel", GTK_RESPONSE_CANCEL, "Save", GTK_RESPONSE_ACCEPT, NULL, NULL);
#line 113 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp0_);
#line 113 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	chooser = _tmp0_;
#line 120 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = chooser;
#line 120 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_show ((GtkWidget*) _tmp1_);
#line 121 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp2_ = chooser;
#line 121 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp3_ = gtk_dialog_run ((GtkDialog*) _tmp2_);
#line 121 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	if (_tmp3_ == ((gint) GTK_RESPONSE_ACCEPT)) {
#line 469 "termites.c"
		gchar* uri = NULL;
		GtkFileChooserDialog* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		TermitesTermiteStore* _tmp7_ = NULL;
		GtkTreeStore* _tmp8_ = NULL;
		GtkTreeStore* _tmp9_ = NULL;
		GtkFileChooserDialog* _tmp10_ = NULL;
#line 122 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp4_ = chooser;
#line 122 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp5_ = gtk_file_chooser_get_uri ((GtkFileChooser*) _tmp4_);
#line 122 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		uri = _tmp5_;
#line 123 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp6_ = uri;
#line 123 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp7_ = self->priv->termite_tree_store;
#line 123 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp8_ = termites_termite_store_get_tree (_tmp7_);
#line 123 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp9_ = _tmp8_;
#line 123 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		termites_file_helper_save_termites_tree (_tmp6_, _tmp9_);
#line 123 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (_tmp9_);
#line 124 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp10_ = chooser;
#line 124 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_signal_emit_by_name ((GtkDialog*) _tmp10_, "close");
#line 121 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_free0 (uri);
#line 502 "termites.c"
	} else {
		GtkFileChooserDialog* _tmp11_ = NULL;
#line 126 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp11_ = chooser;
#line 126 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_signal_emit_by_name ((GtkDialog*) _tmp11_, "close");
#line 509 "termites.c"
	}
#line 112 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (chooser);
#line 513 "termites.c"
}


static void _termites_termites_save_tree_as_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_save_tree_as ((TermitesTermites*) self);
#line 520 "termites.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 137 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	return self ? g_object_ref (self) : NULL;
#line 527 "termites.c"
}


void termites_termites_about_termites (TermitesTermites* self) {
	GError * _inner_error_ = NULL;
#line 131 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (self != NULL);
#line 535 "termites.c"
	{
		GtkBuilder* builder = NULL;
		GtkBuilder* _tmp0_ = NULL;
		GtkAboutDialog* window = NULL;
		GObject* _tmp1_ = NULL;
		GtkAboutDialog* _tmp2_ = NULL;
		GtkAboutDialog* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GtkAboutDialog* _tmp6_ = NULL;
		GtkAboutDialog* _tmp7_ = NULL;
#line 133 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp0_ = gtk_builder_new ();
#line 133 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		builder = _tmp0_;
#line 134 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		gtk_builder_add_from_file (builder, TERMITES_UI_ABOUT, &_inner_error_);
#line 134 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 134 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			_g_object_unref0 (builder);
#line 557 "termites.c"
			goto __catch1_g_error;
		}
#line 135 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		gtk_builder_connect_signals (builder, NULL);
#line 137 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp1_ = gtk_builder_get_object (builder, "aboutTermites");
#line 137 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, gtk_about_dialog_get_type ()) ? ((GtkAboutDialog*) _tmp1_) : NULL);
#line 137 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		window = _tmp2_;
#line 138 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp3_ = window;
#line 138 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp4_ = termites_application_get_version_string ();
#line 138 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp5_ = _tmp4_;
#line 138 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		gtk_about_dialog_set_version (_tmp3_, _tmp5_);
#line 138 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_free0 (_tmp5_);
#line 139 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp6_ = window;
#line 139 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		gtk_window_set_transient_for ((GtkWindow*) _tmp6_, (GtkWindow*) self);
#line 140 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp7_ = window;
#line 140 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		gtk_widget_show_all ((GtkWidget*) _tmp7_);
#line 132 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (window);
#line 132 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (builder);
#line 590 "termites.c"
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
		FILE* _tmp8_ = NULL;
		GError* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
#line 132 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		e = _inner_error_;
#line 132 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_inner_error_ = NULL;
#line 144 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp8_ = stderr;
#line 144 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp9_ = e;
#line 144 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp10_ = _tmp9_->message;
#line 144 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		fprintf (_tmp8_, "Could not load UI: %s\n", _tmp10_);
#line 132 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_error_free0 (e);
#line 613 "termites.c"
	}
	__finally1:
#line 132 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 132 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 132 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_clear_error (&_inner_error_);
#line 132 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		return;
#line 624 "termites.c"
	}
}


static void _termites_termites_about_termites_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_about_termites ((TermitesTermites*) self);
#line 632 "termites.c"
}


void termites_termites_create_node (TermitesTermites* self) {
	TermitesNodeProperties* nodeProp = NULL;
	TermitesNodeProperties* _tmp0_ = NULL;
#line 149 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (self != NULL);
#line 151 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = termites_node_properties_new_new (&self->priv->termite_tree_store);
#line 151 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp0_);
#line 151 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	nodeProp = _tmp0_;
#line 152 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_node_properties_show_window (nodeProp, (GtkWindow*) self);
#line 149 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (nodeProp);
#line 651 "termites.c"
}


static void _termites_termites_create_node_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_create_node ((TermitesTermites*) self);
#line 658 "termites.c"
}


void termites_termites_modify_node (TermitesTermites* self) {
	GtkTreeSelection* selected_node = NULL;
	GtkTreeView* _tmp0_ = NULL;
	GtkTreeSelection* _tmp1_ = NULL;
	GtkTreeSelection* _tmp2_ = NULL;
	TermitesNodeProperties* nodeProp = NULL;
	TermitesNodeProperties* _tmp3_ = NULL;
#line 156 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (self != NULL);
#line 158 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = self->priv->terminalTreeview;
#line 158 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = gtk_tree_view_get_selection (_tmp0_);
#line 158 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 158 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	selected_node = _tmp2_;
#line 161 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp3_ = termites_node_properties_new_edit (&self->priv->termite_tree_store, selected_node);
#line 161 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp3_);
#line 161 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	nodeProp = _tmp3_;
#line 162 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_node_properties_show_window (nodeProp, (GtkWindow*) self);
#line 156 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (nodeProp);
#line 156 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (selected_node);
#line 691 "termites.c"
}


static void _termites_termites_modify_node_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_modify_node ((TermitesTermites*) self);
#line 698 "termites.c"
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_atomic_int_inc (&_data2_->_ref_count_);
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	return _data2_;
#line 707 "termites.c"
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
#line 716 "termites.c"
		TermitesTermites* self;
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		self = _data2_->self;
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (_data2_->msg);
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (self);
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_slice_free (Block2Data, _data2_);
#line 726 "termites.c"
	}
}


static void __lambda5_ (Block2Data* _data2_, gint response_id) {
	TermitesTermites* self;
	gint _tmp0_ = 0;
#line 174 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	self = _data2_->self;
#line 175 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = response_id;
#line 175 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	switch (_tmp0_) {
#line 175 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		case GTK_RESPONSE_YES:
#line 742 "termites.c"
		{
			TermitesTermiteStore* _tmp1_ = NULL;
			GtkTreeIter _tmp2_ = {0};
#line 177 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			_tmp1_ = self->priv->termite_tree_store;
#line 177 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			_tmp2_ = _data2_->node_emplacement;
#line 177 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			termites_termite_store_delete_node (_tmp1_, &_tmp2_);
#line 178 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			break;
#line 754 "termites.c"
		}
		default:
#line 175 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		break;
#line 759 "termites.c"
	}
#line 181 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_destroy ((GtkWidget*) _data2_->msg);
#line 763 "termites.c"
}


static void ___lambda5__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
#line 174 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	__lambda5_ (self, response_id);
#line 770 "termites.c"
}


void termites_termites_remove_node (TermitesTermites* self) {
	Block2Data* _data2_;
	GtkTreeSelection* selected_node = NULL;
	GtkTreeView* _tmp0_ = NULL;
	GtkTreeSelection* _tmp1_ = NULL;
	GtkTreeSelection* _tmp2_ = NULL;
	GtkTreeModel* model = NULL;
	GtkTreeModel* _tmp3_ = NULL;
	GtkTreeIter _tmp4_ = {0};
	GtkTreeModel* _tmp5_ = NULL;
	GtkMessageDialog* _tmp6_ = NULL;
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (self != NULL);
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data2_ = g_slice_new0 (Block2Data);
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data2_->_ref_count_ = 1;
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data2_->self = g_object_ref (self);
#line 167 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = self->priv->terminalTreeview;
#line 167 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = gtk_tree_view_get_selection (_tmp0_);
#line 167 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 167 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	selected_node = _tmp2_;
#line 171 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_tree_selection_get_selected (selected_node, &_tmp3_, &_tmp4_);
#line 171 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (model);
#line 171 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp5_ = _g_object_ref0 (_tmp3_);
#line 171 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	model = _tmp5_;
#line 171 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data2_->node_emplacement = _tmp4_;
#line 173 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp6_ = (GtkMessageDialog*) gtk_message_dialog_new ((GtkWindow*) self, GTK_DIALOG_MODAL, GTK_MESSAGE_WARNING, GTK_BUTTONS_YES_NO, "Are you sure you want to delete this node?");
#line 173 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp6_);
#line 173 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data2_->msg = _tmp6_;
#line 174 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_signal_connect_data ((GtkDialog*) _data2_->msg, "response", (GCallback) ___lambda5__gtk_dialog_response, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 183 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_show ((GtkWidget*) _data2_->msg);
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (model);
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (selected_node);
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	block2_data_unref (_data2_);
#line 166 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data2_ = NULL;
#line 829 "termites.c"
}


static void _termites_termites_remove_node_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_remove_node ((TermitesTermites*) self);
#line 836 "termites.c"
}


static Block3Data* block3_data_ref (Block3Data* _data3_) {
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_atomic_int_inc (&_data3_->_ref_count_);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	return _data3_;
#line 845 "termites.c"
}


static void block3_data_unref (void * _userdata_) {
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
#line 854 "termites.c"
		TermitesTermites* self;
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		self = _data3_->self;
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (_data3_->testTerm);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (self);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_slice_free (Block3Data, _data3_);
#line 864 "termites.c"
	}
}


static void ___lambda6_ (Block3Data* _data3_, gint t) {
	TermitesTermites* self;
	GtkNotebook* _tmp0_ = NULL;
	VteTerminal* _tmp1_ = NULL;
#line 213 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	self = _data3_->self;
#line 213 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = self->priv->terminalTabs;
#line 213 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = _data3_->testTerm;
#line 213 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_container_remove ((GtkContainer*) _tmp0_, (GtkWidget*) _tmp1_);
#line 881 "termites.c"
}


static void ____lambda6__vte_terminal_child_exited (VteTerminal* _sender, gint status, gpointer self) {
#line 213 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	___lambda6_ (self, status);
#line 888 "termites.c"
}


void termites_termites_open_connection (TermitesTermites* self, GtkTreeView* p_view, GtkTreePath* p_root, GtkTreeViewColumn* p_column) {
	Block3Data* _data3_;
	GtkTreeIter iter = {0};
	TermitesTermiteNode* node = NULL;
	GtkTreeView* _tmp0_ = NULL;
	GtkTreeModel* _tmp1_ = NULL;
	GtkTreeModel* _tmp2_ = NULL;
	GtkTreePath* _tmp3_ = NULL;
	GtkTreeIter _tmp4_ = {0};
	gboolean _tmp5_ = FALSE;
	gchar** env_var = NULL;
	const gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar** _tmp22_ = NULL;
	gint env_var_length1 = 0;
	gint _env_var_size_ = 0;
	gchar** interpreter = NULL;
	gchar* _tmp23_ = NULL;
	TermitesTermiteNode* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	gchar** _tmp26_ = NULL;
	gint interpreter_length1 = 0;
	gint _interpreter_size_ = 0;
	gchar* dir = NULL;
	gchar* _tmp27_ = NULL;
	VteTerminal* _tmp28_ = NULL;
	VteTerminal* _tmp29_ = NULL;
	GError * _inner_error_ = NULL;
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (self != NULL);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (p_view != NULL);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (p_root != NULL);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (p_column != NULL);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data3_ = g_slice_new0 (Block3Data);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data3_->_ref_count_ = 1;
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data3_->self = g_object_ref (self);
#line 190 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	node = NULL;
#line 191 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = p_view;
#line 191 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = gtk_tree_view_get_model (_tmp0_);
#line 191 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp2_ = _tmp1_;
#line 191 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp3_ = p_root;
#line 191 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp5_ = gtk_tree_model_get_iter (_tmp2_, &_tmp4_, _tmp3_);
#line 191 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	iter = _tmp4_;
#line 191 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	if (_tmp5_) {
#line 950 "termites.c"
		GtkTreeView* _tmp6_ = NULL;
		GtkTreeModel* _tmp7_ = NULL;
		GtkTreeModel* _tmp8_ = NULL;
		GtkTreeIter _tmp9_ = {0};
		TermitesTermiteNode* _tmp10_ = NULL;
		TermitesTermiteNode* _tmp11_ = NULL;
		const gchar* _tmp12_ = NULL;
		const gchar* _tmp13_ = NULL;
		FILE* _tmp14_ = NULL;
		TermitesTermiteNode* _tmp15_ = NULL;
		gchar* _tmp16_ = NULL;
		gchar* _tmp17_ = NULL;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
#line 192 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp6_ = p_view;
#line 192 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp7_ = gtk_tree_view_get_model (_tmp6_);
#line 192 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp8_ = _tmp7_;
#line 192 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp9_ = iter;
#line 192 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp10_ = termites_termites_get_selection (_tmp8_, &_tmp9_);
#line 192 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (node);
#line 192 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		node = _tmp10_;
#line 193 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp11_ = node;
#line 193 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp12_ = termites_termite_node_get_host (_tmp11_);
#line 193 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp13_ = _tmp12_;
#line 193 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		if (_tmp13_ == NULL) {
#line 194 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			_g_object_unref0 (node);
#line 194 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			block3_data_unref (_data3_);
#line 194 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			_data3_ = NULL;
#line 194 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			return;
#line 995 "termites.c"
		}
#line 197 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp14_ = stdout;
#line 197 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp15_ = node;
#line 197 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp16_ = termites_termite_node_serialize (_tmp15_);
#line 197 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp17_ = _tmp16_;
#line 197 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp18_ = g_strconcat (_tmp17_, "\n", NULL);
#line 197 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp19_ = _tmp18_;
#line 197 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		fprintf (_tmp14_, "%s", _tmp19_);
#line 197 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_free0 (_tmp19_);
#line 197 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_free0 (_tmp17_);
#line 1015 "termites.c"
	}
#line 200 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp20_ = g_getenv ("PROMPT_COMMAND");
#line 200 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp21_ = g_strconcat ("PROMPT_COMMAND=", _tmp20_, NULL);
#line 200 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp22_ = g_new0 (gchar*, 1 + 1);
#line 200 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp22_[0] = _tmp21_;
#line 200 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	env_var = _tmp22_;
#line 200 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	env_var_length1 = 1;
#line 200 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_env_var_size_ = env_var_length1;
#line 201 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp23_ = g_strdup (TERMITES_SSH_BINARY_PATH);
#line 201 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp24_ = node;
#line 201 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp25_ = termites_termite_node_get_connection_string (_tmp24_);
#line 201 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp26_ = g_new0 (gchar*, 2 + 1);
#line 201 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp26_[0] = _tmp23_;
#line 201 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp26_[1] = _tmp25_;
#line 201 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	interpreter = _tmp26_;
#line 201 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	interpreter_length1 = 2;
#line 201 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_interpreter_size_ = interpreter_length1;
#line 203 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp27_ = g_get_current_dir ();
#line 203 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	dir = _tmp27_;
#line 204 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp28_ = (VteTerminal*) vte_terminal_new ();
#line 204 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp28_);
#line 204 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data3_->testTerm = _tmp28_;
#line 205 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp29_ = _data3_->testTerm;
#line 205 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp29_, TRUE);
#line 1063 "termites.c"
	{
		VtePty* termPty = NULL;
		VtePty* _tmp30_ = NULL;
		VteTerminal* _tmp31_ = NULL;
		VtePty* _tmp32_ = NULL;
		VteTerminal* _tmp33_ = NULL;
		VteTerminal* _tmp34_ = NULL;
		const gchar* _tmp35_ = NULL;
		gchar** _tmp36_ = NULL;
		gint _tmp36__length1 = 0;
		gchar** _tmp37_ = NULL;
		gint _tmp37__length1 = 0;
		gint tab_number = 0;
		GtkNotebook* _tmp38_ = NULL;
		VteTerminal* _tmp39_ = NULL;
		TermitesTermiteNode* _tmp40_ = NULL;
		const gchar* _tmp41_ = NULL;
		const gchar* _tmp42_ = NULL;
		VteTerminal* _tmp43_ = NULL;
		GtkWidget* _tmp44_ = NULL;
		GtkWidget* _tmp45_ = NULL;
		gint _tmp46_ = 0;
		gint _tmp47_ = 0;
		GtkNotebook* _tmp48_ = NULL;
		VteTerminal* _tmp49_ = NULL;
		GtkNotebook* _tmp50_ = NULL;
		gint _tmp51_ = 0;
		VteTerminal* _tmp52_ = NULL;
#line 208 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp30_ = vte_pty_new_sync (VTE_PTY_DEFAULT, NULL, &_inner_error_);
#line 208 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		termPty = _tmp30_;
#line 208 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1098 "termites.c"
			goto __catch2_g_error;
		}
#line 209 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp31_ = _data3_->testTerm;
#line 209 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp32_ = termPty;
#line 209 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		vte_terminal_set_pty (_tmp31_, _tmp32_);
#line 213 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp33_ = _data3_->testTerm;
#line 213 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_signal_connect_data (_tmp33_, "child-exited", (GCallback) ____lambda6__vte_terminal_child_exited, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
#line 216 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp34_ = _data3_->testTerm;
#line 216 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp35_ = dir;
#line 216 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp36_ = interpreter;
#line 216 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp36__length1 = interpreter_length1;
#line 216 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp37_ = env_var;
#line 216 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp37__length1 = env_var_length1;
#line 216 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		vte_terminal_spawn_sync (_tmp34_, VTE_PTY_DEFAULT, _tmp35_, _tmp36_, _tmp37_, G_SPAWN_DO_NOT_REAP_CHILD, NULL, NULL, NULL, NULL, &_inner_error_);
#line 216 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 216 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			_g_object_unref0 (termPty);
#line 1129 "termites.c"
			goto __catch2_g_error;
		}
#line 220 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp38_ = self->priv->terminalTabs;
#line 220 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp39_ = _data3_->testTerm;
#line 220 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp40_ = node;
#line 220 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp41_ = termites_termite_node_get_name (_tmp40_);
#line 220 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp42_ = _tmp41_;
#line 220 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp43_ = _data3_->testTerm;
#line 220 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp44_ = termites_termites_create_notebook_child_label (self, _tmp42_, (GtkWidget*) _tmp43_);
#line 220 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp45_ = _tmp44_;
#line 220 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp46_ = gtk_notebook_append_page (_tmp38_, (GtkWidget*) _tmp39_, _tmp45_);
#line 220 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp47_ = _tmp46_;
#line 220 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (_tmp45_);
#line 220 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		tab_number = _tmp47_;
#line 222 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp48_ = self->priv->terminalTabs;
#line 222 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp49_ = _data3_->testTerm;
#line 222 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		gtk_notebook_set_tab_reorderable (_tmp48_, (GtkWidget*) _tmp49_, TRUE);
#line 223 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		termites_termites_reorganise_tabs (self);
#line 226 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp50_ = self->priv->terminalTabs;
#line 226 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp51_ = tab_number;
#line 226 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		gtk_notebook_set_current_page (_tmp50_, _tmp51_);
#line 227 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp52_ = _data3_->testTerm;
#line 227 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_object_set ((GtkWidget*) _tmp52_, "has-focus", TRUE, NULL);
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (termPty);
#line 1176 "termites.c"
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* e = NULL;
		FILE* _tmp53_ = NULL;
		GError* _tmp54_ = NULL;
		const gchar* _tmp55_ = NULL;
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		e = _inner_error_;
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_inner_error_ = NULL;
#line 229 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp53_ = stderr;
#line 229 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp54_ = e;
#line 229 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp55_ = _tmp54_->message;
#line 229 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		fprintf (_tmp53_, "Error happened: %s\n", _tmp55_);
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_error_free0 (e);
#line 1199 "termites.c"
	}
	__finally2:
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_free0 (dir);
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		interpreter = (_vala_array_free (interpreter, interpreter_length1, (GDestroyNotify) g_free), NULL);
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		env_var = (_vala_array_free (env_var, env_var_length1, (GDestroyNotify) g_free), NULL);
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (node);
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		block3_data_unref (_data3_);
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_data3_ = NULL;
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_clear_error (&_inner_error_);
#line 207 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		return;
#line 1222 "termites.c"
	}
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_free0 (dir);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	interpreter = (_vala_array_free (interpreter, interpreter_length1, (GDestroyNotify) g_free), NULL);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	env_var = (_vala_array_free (env_var, env_var_length1, (GDestroyNotify) g_free), NULL);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (node);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	block3_data_unref (_data3_);
#line 187 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data3_ = NULL;
#line 1236 "termites.c"
}


static void _termites_termites_open_connection_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_open_connection ((TermitesTermites*) self, _sender, path, column);
#line 1243 "termites.c"
}


void termites_termites_reorganise_tabs (TermitesTermites* self) {
	GtkNotebook* _tmp0_ = NULL;
	gint _tmp1_ = 0;
#line 234 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (self != NULL);
#line 237 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = self->priv->terminalTabs;
#line 237 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = gtk_notebook_get_n_pages (_tmp0_);
#line 237 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	if (_tmp1_ == 0) {
#line 1258 "termites.c"
		GtkNotebook* _tmp2_ = NULL;
		GtkLabel* _tmp3_ = NULL;
		GtkNotebook* _tmp4_ = NULL;
#line 238 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp2_ = self->priv->terminalTabs;
#line 238 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp3_ = self->priv->lblSession;
#line 238 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		gtk_notebook_append_page (_tmp2_, (GtkWidget*) _tmp3_, NULL);
#line 239 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp4_ = self->priv->terminalTabs;
#line 239 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		gtk_notebook_set_show_tabs (_tmp4_, FALSE);
#line 1272 "termites.c"
	} else {
		GtkNotebook* _tmp5_ = NULL;
		GtkLabel* _tmp6_ = NULL;
		gint _tmp7_ = 0;
#line 240 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp5_ = self->priv->terminalTabs;
#line 240 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp6_ = self->priv->lblSession;
#line 240 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_tmp7_ = gtk_notebook_page_num (_tmp5_, (GtkWidget*) _tmp6_);
#line 240 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		if (_tmp7_ > (-1)) {
#line 1285 "termites.c"
			GtkNotebook* _tmp8_ = NULL;
			GtkLabel* _tmp9_ = NULL;
			GtkNotebook* _tmp10_ = NULL;
#line 241 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			_tmp8_ = self->priv->terminalTabs;
#line 241 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			_tmp9_ = self->priv->lblSession;
#line 241 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			gtk_container_remove ((GtkContainer*) _tmp8_, (GtkWidget*) _tmp9_);
#line 242 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			_tmp10_ = self->priv->terminalTabs;
#line 242 "/home/vincent/Source/Vala/Termites/src/termites.vala"
			gtk_notebook_set_show_tabs (_tmp10_, TRUE);
#line 1299 "termites.c"
		}
	}
}


static void _termites_termites_reorganise_tabs_gtk_notebook_page_removed (GtkNotebook* _sender, GtkWidget* child, guint page_num, gpointer self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_reorganise_tabs ((TermitesTermites*) self);
#line 1308 "termites.c"
}


void termites_termites_open_settings (TermitesTermites* self) {
	TermitesConfig* _tmp0_ = NULL;
	TermitesConfig* _tmp1_ = NULL;
#line 247 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (self != NULL);
#line 248 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = self->priv->m_configuration;
#line 248 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_window_set_transient_for ((GtkWindow*) _tmp0_, (GtkWindow*) self);
#line 249 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = self->priv->m_configuration;
#line 249 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp1_);
#line 1325 "termites.c"
}


static void _termites_termites_open_settings_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_open_settings ((TermitesTermites*) self);
#line 1332 "termites.c"
}


static TermitesTermiteNode* termites_termites_get_selection (GtkTreeModel* p_model, GtkTreeIter* p_iter) {
	TermitesTermiteNode* result = NULL;
	GValue node_from_tree = {0};
	GtkTreeModel* _tmp0_ = NULL;
	GtkTreeIter _tmp1_ = {0};
	GValue _tmp2_ = {0};
	TermitesTermiteNode* node = NULL;
	GValue _tmp3_ = {0};
	TermitesTermiteNode* _tmp4_ = NULL;
#line 252 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_val_if_fail (p_model != NULL, NULL);
#line 252 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_val_if_fail (p_iter != NULL, NULL);
#line 254 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = p_model;
#line 254 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = *p_iter;
#line 254 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_tree_model_get_value (_tmp0_, &_tmp1_, 1, &_tmp2_);
#line 254 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	G_IS_VALUE (&node_from_tree) ? (g_value_unset (&node_from_tree), NULL) : NULL;
#line 254 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	node_from_tree = _tmp2_;
#line 255 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp3_ = node_from_tree;
#line 255 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp4_ = _g_object_ref0 (g_value_get_object (&_tmp3_));
#line 255 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	node = _tmp4_;
#line 256 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	result = node;
#line 256 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	G_IS_VALUE (&node_from_tree) ? (g_value_unset (&node_from_tree), NULL) : NULL;
#line 256 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	return result;
#line 1371 "termites.c"
}


static Block4Data* block4_data_ref (Block4Data* _data4_) {
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_atomic_int_inc (&_data4_->_ref_count_);
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	return _data4_;
#line 1380 "termites.c"
}


static void block4_data_unref (void * _userdata_) {
	Block4Data* _data4_;
	_data4_ = (Block4Data*) _userdata_;
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	if (g_atomic_int_dec_and_test (&_data4_->_ref_count_)) {
#line 1389 "termites.c"
		TermitesTermites* self;
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		self = _data4_->self;
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (_data4_->p_term_tab);
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		_g_object_unref0 (self);
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
		g_slice_free (Block4Data, _data4_);
#line 1399 "termites.c"
	}
}


static void __lambda7_ (Block4Data* _data4_, GtkButton* t) {
	TermitesTermites* self;
	GtkNotebook* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
#line 273 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	self = _data4_->self;
#line 273 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_if_fail (t != NULL);
#line 273 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = self->priv->terminalTabs;
#line 273 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = _data4_->p_term_tab;
#line 273 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_container_remove ((GtkContainer*) _tmp0_, _tmp1_);
#line 1418 "termites.c"
}


static void ___lambda7__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 273 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	__lambda7_ (self, _sender);
#line 1425 "termites.c"
}


static GtkWidget* termites_termites_create_notebook_child_label (TermitesTermites* self, const gchar* p_text, GtkWidget* p_term_tab) {
	GtkWidget* result = NULL;
	Block4Data* _data4_;
	GtkWidget* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
	GtkLabel* label = NULL;
	const gchar* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkImage* image = NULL;
	GtkImage* _tmp4_ = NULL;
	GtkButton* button = NULL;
	GtkButton* _tmp5_ = NULL;
	GtkBox* box = NULL;
	GtkBox* _tmp6_ = NULL;
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_val_if_fail (p_text != NULL, NULL);
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_return_val_if_fail (p_term_tab != NULL, NULL);
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data4_ = g_slice_new0 (Block4Data);
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data4_->_ref_count_ = 1;
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data4_->self = g_object_ref (self);
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp0_ = p_term_tab;
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (_data4_->p_term_tab);
#line 259 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data4_->p_term_tab = _tmp1_;
#line 262 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp2_ = p_text;
#line 262 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp3_ = (GtkLabel*) gtk_label_new (_tmp2_);
#line 262 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp3_);
#line 262 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	label = _tmp3_;
#line 263 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp4_ = (GtkImage*) gtk_image_new_from_icon_name (GTK_STOCK_CLOSE, GTK_ICON_SIZE_MENU);
#line 263 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp4_);
#line 263 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	image = _tmp4_;
#line 265 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp5_ = (GtkButton*) gtk_button_new ();
#line 265 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp5_);
#line 265 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	button = _tmp5_;
#line 266 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_button_set_relief (button, GTK_RELIEF_NONE);
#line 267 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_set_name ((GtkWidget*) button, "sample-close-tab-button");
#line 269 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_button_set_focus_on_click (button, FALSE);
#line 270 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_container_add ((GtkContainer*) button, (GtkWidget*) image);
#line 273 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_signal_connect_data (button, "clicked", (GCallback) ___lambda7__gtk_button_clicked, block4_data_ref (_data4_), (GClosureNotify) block4_data_unref, 0);
#line 275 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_tmp6_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 2);
#line 275 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_object_ref_sink (_tmp6_);
#line 275 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	box = _tmp6_;
#line 276 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_box_pack_start (box, (GtkWidget*) label, FALSE, FALSE, (guint) 0);
#line 277 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_box_pack_start (box, (GtkWidget*) button, FALSE, FALSE, (guint) 0);
#line 278 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_show_all ((GtkWidget*) box);
#line 280 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	result = (GtkWidget*) box;
#line 280 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (button);
#line 280 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (image);
#line 280 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (label);
#line 280 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	block4_data_unref (_data4_);
#line 280 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_data4_ = NULL;
#line 280 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	return result;
#line 1519 "termites.c"
}


static void termites_termites_class_init (TermitesTermitesClass * klass) {
	gint TermitesTermites_private_offset;
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	termites_termites_parent_class = g_type_class_peek_parent (klass);
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	g_type_class_add_private (klass, sizeof (TermitesTermitesPrivate));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	G_OBJECT_CLASS (klass)->finalize = termites_termites_finalize;
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	TermitesTermites_private_offset = g_type_class_get_instance_private_offset (klass);
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/termites/ui/termites.ui");
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "terminalTreeview", FALSE, TermitesTermites_private_offset + G_STRUCT_OFFSET (TermitesTermitesPrivate, terminalTreeview));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "terminalTabs", FALSE, TermitesTermites_private_offset + G_STRUCT_OFFSET (TermitesTermitesPrivate, terminalTabs));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "lblSession", FALSE, TermitesTermites_private_offset + G_STRUCT_OFFSET (TermitesTermitesPrivate, lblSession));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_destroy", G_CALLBACK(_termites_termites_on_destroy_gtk_widget_destroy));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "quit_termites", G_CALLBACK(_termites_termites_quit_termites_gtk_menu_item_activate));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "open_tree", G_CALLBACK(_termites_termites_open_tree_gtk_menu_item_activate));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "save_tree", G_CALLBACK(_termites_termites_save_tree_gtk_menu_item_activate));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "save_tree_as", G_CALLBACK(_termites_termites_save_tree_as_gtk_menu_item_activate));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "about_termites", G_CALLBACK(_termites_termites_about_termites_gtk_menu_item_activate));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "create_node", G_CALLBACK(_termites_termites_create_node_gtk_menu_item_activate));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "modify_node", G_CALLBACK(_termites_termites_modify_node_gtk_menu_item_activate));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "remove_node", G_CALLBACK(_termites_termites_remove_node_gtk_menu_item_activate));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "open_connection", G_CALLBACK(_termites_termites_open_connection_gtk_tree_view_row_activated));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "reorganise_tabs", G_CALLBACK(_termites_termites_reorganise_tabs_gtk_notebook_page_removed));
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "open_settings", G_CALLBACK(_termites_termites_open_settings_gtk_menu_item_activate));
#line 1565 "termites.c"
}


static void termites_termites_instance_init (TermitesTermites * self) {
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	self->priv = TERMITES_TERMITES_GET_PRIVATE (self);
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 1574 "termites.c"
}


static void termites_termites_finalize (GObject* obj) {
	TermitesTermites * self;
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TERMITES_TYPE_TERMITES, TermitesTermites);
#line 40 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (self->priv->terminalTreeview);
#line 43 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (self->priv->terminalTabs);
#line 46 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (self->priv->lblSession);
#line 48 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (self->priv->termite_tree_store);
#line 50 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	_g_object_unref0 (self->priv->m_configuration);
#line 37 "/home/vincent/Source/Vala/Termites/src/termites.vala"
	G_OBJECT_CLASS (termites_termites_parent_class)->finalize (obj);
#line 1594 "termites.c"
}


GType termites_termites_get_type (void) {
	static volatile gsize termites_termites_type_id__volatile = 0;
	if (g_once_init_enter (&termites_termites_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TermitesTermitesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) termites_termites_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TermitesTermites), 0, (GInstanceInitFunc) termites_termites_instance_init, NULL };
		GType termites_termites_type_id;
		termites_termites_type_id = g_type_register_static (gtk_application_window_get_type (), "TermitesTermites", &g_define_type_info, 0);
		g_once_init_leave (&termites_termites_type_id__volatile, termites_termites_type_id);
	}
	return termites_termites_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



